### PR TITLE
Make fit_NGC6440E into documentation

### PR DESCRIPTION
**Pull request by aarchiba**
In #1071 we had some problems where changes broke `fit_NCG6440E.py` but it was never tested as part of CI. This change makes it part of our documentation - as a tutorial, rendered as a notebook - and as a result failures to run will result in CI failures. This can still be run as a `.py` file (and is downloadable from the tutorial page) but will also be visible in our documentation.

I also updated certain code to more modern approaches.

### CODE REVIEW

**Comment by aarchiba** [comment]
The notebooks are the only test this could really break and those are fine - we're having ephemeris server problems :-P 

New tutorial at: https://nanograv-pint--1089.org.readthedocs.build/en/1089/examples/fit_NGC6440E.html

**Comment by aarchiba** [comment]
The bogus `get_summary` result is fixed in #1071.

**Comment by aarchiba** [comment]
Ready for review and merging.

**Comment by dlakaplan** [comment]
This looks fine to me.  It's minor enough that I can merge if nobody objects.

**Comment by aarchiba** [comment]
Go for it!

**Pull request merged**
