### PR TITLE
Added TOA method to select and unselect TOAs using boolean arrays

### PR DESCRIPTION
**Pull request by scottransom**
OK.  Check this out.  This makes a stack-based way of selecting groups of TOAs using boolean arrays.  It changes the .ntoas and .observatories attributes into properties.  And makes a simple method for allowing the selection.  There are examples of usage in fit_NGC6440E.py

### CODE REVIEW

**Comment by paulray** [comment]
I like!

Maybe just add a unit test that pushes a couple and pops a couple of selections.

**Comment by scottransom** [comment]
Take a peek and if you like it, feel free to merge.

**Comment by paulray** [comment]
properties are cool!

**Comment by luojing1211** [comment]
It is super cool that we can apply multiple selection on TOAs. My question
is that it will undo select by the backwards order. Do we need to provide
the functionality for unselecting by telling the program which selection to
be unselected?

- Jing Luo

**Comment by scottransom** [comment]
I don't think that would be super useful.  It would be kind of hard to figure out what has been selected in each version if you made a bunch of different selects.  probably better to .pop() all the way back to the beginning and select again.  But maybe I'm wrong.

**Comment by paulray** [comment]
I'd wait on adding additional complexity until there is a particular use case driving the need to undo in some particular order different than what you get with this stack-based approach.

**Pull request merged**
