### PR TITLE
Clean up and test derivative calculations

### LINKED ISSUE #1053: designmatrix returns the wrong units for offset
All other units in the design matrix are appropriate for derivatives of TOA (or residual) with respect to the parameter, but the offset is unitless instead of having units of time. This is actually special-cased to be wrong in the code.

The documentation in the design matrix also fails to include mention of what a comment indicates is a surprising minus sign.

The code also ignores the units returned from derivative functions, so incompatible units do not lead to an exception, and unusual units (days instead of seconds) are not converted.

### LINKED ISSUE #1054: Tests are order-dependent
Some of PINT's tests depend on being executed in a specific order. This shows in that many tests fail if run in parallel with `pytest-xdist`, or if run in random order using the pytest plugin that does that, or if the specific tests are run in isolation with `pytest tests/test_file.py::test_specific_thing`. Since the PINT test suite is slow, `pytest-xdist` would otherwise allow speedup by about the number of cores available, and running individual tests is very helpful. More, tests that depend on other tests make interpreting test failures to localize bugs quite challenging.

Tests observed to fail under such conditions:

- `tests/test_toa_selection.py::TestTOAselection::test_hash`
- `tests/test_ddk.py::TestDDK::test_J1713_deriv`

### PR DESCRIPTION
**Pull request by aarchiba**
The goal is to document and fix problems in PINT's derivative calculations. This includes using numdifftools to check the analytical derivatives against finite differences computed from the model.

Closes #1053 
Closes #1054 (now you can use pytest-xdist to run the test suite faster!)

### CODE REVIEW

**Comment by scottransom** [comment]
Yay!  Nice job!  This is something that we've talked about for years!

**Comment by aarchiba** [comment]
> Yay! Nice job! This is something that we've talked about for years!

Tons of failures :-P A few are numdifftools being ill-behaved, but others seem to be PINT problems - for example, if the A1DOT gets the magic TEMPO-compatibility rescaling, its derivative does not. (And recall that Fitters rely on these derivatives to update model values...) I'm not sure what the issue is with FBn, but the derivative seems to be wrong by several orders of magnitude.

**Comment by scottransom** [comment]
Not surprised.  Which is exactly why we've been talking about this!  Thanks for the efforts!

**Comment by aarchiba** [comment]
`A1DOT` is sort of okay, it was an unexpected interaction between `numdifftools` and PINT's automatic rescaling of `A1DOT` (see #1057). It looks like probably `H3` and `FBn` do have errors, though.

**Comment by scottransom** [comment]
This PR should reference issue #751

**Comment by scottransom** [comment]
I'm kind of surprised by the failure of the `FBX` derivs since those use `taylor_horner_deriv()`, which I thought was good!

**Comment by scottransom** [comment]
Although there doesn't seem to be any tests for `taylor_horner_deriv()` as there is for `taylor_horner()` itself...  That is definitely an omission!

**Comment by aarchiba** [comment]
It seems very possible that there is a unit or offset error in the calculation of the `FBn` derivatives - they seem to be off by orders of magnitude. Or my test points are too far from `T0` and round-off is producing junk, but they don't look *that* bad.

**Comment by aarchiba** [comment]
https://nanograv-pint--1056.org.readthedocs.build/en/1056/api/pint.models.timing_model.html#pint.models.timing_model.TimingModel The cleanup is meant to improve the documentation, which you can check for the PR here.

**Comment by aarchiba** [comment]
Status update:

- `FBn` - with appropriate step sizes for the derivative values seem to be... close. Unclear whether there are real discrepancies yet. The pure orbital code seems much more accurate.
- `H3` - it appears that `ELL1H` uses Fourier series unnecessarily, and uses different approximations in the derivative and in the delay calculation.

I am currently working on tools for using and testing `H3`/`H4`/`VARSIGMA` in all models, not just `ELL1H`, so I might just mark the `H3` tests as `xfail` until that code sorts it out.

**Comment by aarchiba** [comment]
I sorted out the numerics for everything else, and set the H3 tests to `xfail`; they need to be fixed elsewhere.

**Comment by scottransom** [comment]
Can you add a test to `taylor_horner_deriv()`?  Seems like that should be explicitly tested since it is used for our derivative calcs, in general.

**Comment by aarchiba** [comment]
Good idea. I did some tests and it's fine - makes the FBn work - but testing it explicitly would be much better.

**Comment by scottransom** [comment]
I;ll merge when the checks pass.  Thanks!

**Comment by scottransom** [comment]
Is that `black` issue legit?

**Comment by aarchiba** [comment]
Forgot to mention in the meeting - you can now use `pytest-xdist` to parallelize the test suite. So I do `pytest -n 80` on my monster server and the whole test suite is over in a couple of minutes. It's *great*.

**Comment by aarchiba** [comment]
Should be good to merge once CI finishes.

**Pull request merged**
