### PR TITLE
Changed 'setup' import in setup.py from setuptools to fix python setu…

### PR DESCRIPTION
**Pull request by vhaasteren**
…p.py develop

The setup import in setup.py now comes from setuptools. I had issues doing

    python setup.py develop

This fixes the issue.

### CODE REVIEW

**Comment by vhaasteren** [comment]
@demorest , I placed this in a PR, since you were also doing something with setup.py. It should be easy to check whether this works, since it is one line.

**Comment by demorest** [comment]
That seems fine to me.  Should we also then import Extension from setuptools rather than distutils?  It actually seems to work either way...

**Comment by vhaasteren** [comment]
I looked up the difference in a bit more detail. distutils is still the standard. Perhaps we should try to import setuptools, and if that fails we default back to distutils for both.

**Comment by demorest** [comment]
Ok, that sounds like a good plan.  Do you want to add those changes into this PR?

**Comment by vhaasteren** [comment]
Yes, done. I'll merge it.

**Pull request merged**
