### PR TITLE
More realistic simulation of narrowband TOAs of multiple frequencies

### PR DESCRIPTION
**Pull request by abhisrkckl**
`multi_freqs_in_epoch` option in `make_fake_toas_uniform` and `make_fake_toas_fromMJDs`.
`--multifreq` option in `zima`
Moved some tests from `test_zima.py` to `test_fake_toas.py`

Note that the default behavior doesn't change.

### CODE REVIEW

**Comment by dlakaplan** [comment]
Can you give an example of how this works here?

**Comment by dlakaplan** [comment]
And can you also add in the docstrings a more explicit explanation of the two modes?

**Comment by dlakaplan** [comment]
Basically if you add in the way you explained this in the issue, that would be great.

**Comment by abhisrkckl** [comment]
> Can you give an example of how this works here?

I have added a new example script `simulation_example.py` which demonstrates the various capabilities of the `pint.simulate` module.


> And can you also add in the docstrings a more explicit explanation of the two modes?
> Basically if you add in the way you explained this in the issue, that would be great.

I have expanded the docstrings with this explanation.

**Comment by dlakaplan** [comment]
Should your new simulation notebook be included in the RTD examples?  I don't think it is yet.

**Comment by dlakaplan** [comment]
Actually I'm not sure about that.  It isn't in the `tutorials.rst` but I still see it at https://nanograv-pint--1670.org.readthedocs.build/en/1670/examples/simulation_example.html

**Comment by abhisrkckl** [comment]
It's there in `tutorials.rst`

**Comment by dlakaplan** [comment]
OK, good.  I didn't see that before in the changed files for whatever reason.  I can then merge this when you are ready.

**Comment by abhisrkckl** [comment]
It can be merged once the tests pass.

**Pull request merged**
