### PR TITLE
added solar wind reference

### PR DESCRIPTION
**Pull request by mtlam**
Solar wind reference added to the docstring to resolve issue #637. There are older ones but this is a rather thorough treatment.

### CODE REVIEW

**Comment by paulray** [comment]
Thanks! That is helpful, but maybe I was too quick in adding my little issue.
My overall goal is to have equations in the mapped to specific literature references. So, while that one is good at the top level, could you also add some comments down around line 68 explaining that the equations being implemented here are Eqns (30) and (31) of Tempo2 paper II?

**Comment by mtlam** [comment]
It's not immediately clear to me how the equations in `solar_wind_delay()` relate to those in the TEMPO2 II paper. The DM is proportional to ρ/(r sin ρ). Is θ defined differently? It sort of looks like it's the other side of the triangle but again it's not immediately clear. If this is okay, I can add some more comments in.

**Comment by luojing1211** [comment]
Feel free to make PR for this.
-Jing

**Comment by paulray** [comment]
This is a PR, @luojing1211 . What are you saying, exactly?  Are you saying the equations might be wrong?  How do they compare to the Tempo2 code, and how does that match the Tempo2 paper?

**Comment by luojing1211** [comment]
Oops, I thought this is an issue. I can not really tell from my email.

**Comment by mtlam** [comment]
I've not looked at the TEMPO2 code, just the definition they give, which I know has been verified by others. I'm not sure what `rsa` is supposed to stand for but it looks like the observatory-Sun vector, which is used to get the radial distance `r`. The variable `pos` presumably means pulsar-Observatory-Sun, which indeed means that θ is not the same as ρ, which is the pulsar-Sun-observatory angle. So I'd have to work through it to see if it matches. If anything, I can add in what those quantities mean in comments.

**Comment by paulray** [comment]
@mtlam were you going to put in those comments on the definitions of the quantities before we merge this?

**Comment by mtlam** [comment]
Yes, at some point... hopefully shortly. I'm still not sure what `rsa` means and was going to ask @luojing1211.

**Comment by mtlam** [comment]
After digging in tempo2 upon suggestion, I found:
`/* Note rsa = vector from observatory to centre of Sun */`
It's used in a number of places. However, I would like to rename this (maybe some others but I'd have to look back), especially since it only appears in this block of PINT code. Can someone else confirm that is okay? I'll add in the appropriate comments, etc.

**Comment by mtlam** [comment]
I have added some more references, renamed one variable, and added a little more documentation to hopefully make it clear that it does in fact relate to the equations given in the TEMPO2 paper.

**Comment by paulray** [comment]
Hmm, lots of test failures even though this is just a few variables renamed. I think this is all due to astropy 4.0.1.

**Comment by mtlam** [comment]
I think that's probably likely. The only variable I ended up renaming was `rsa` in the end; I just added comments to what the new one, `pos`, `theta` represented.

**Comment by paulray** [comment]
OK, my suggestion is to split up these two issues.  Can  you add <4.0.1 to the astropy lines in requirements*.txt and setup.cfg and see if that makes all your tests pass. Then we should create a separate issue on astropy 4.0.1 breaking PINT.

**Comment by paulray** [comment]
Actually, I forgot that the master branch already has the astropy<=4.0 so you can just rebase on master.

**Comment by paulray** [comment]
Sorry to post again, but I should not have said rebase. It is bad to rebase after already pushing a branch. What you want to do is merge master into your PR, or we could just merge this PR and that will do it.  In fact, that is the easiest thing to do so I'll just merge this now.

**Comment by demorest** [comment]
@paulray I already started #651 about astropy 4.0.1 issues.

**Pull request merged**
