### PR TITLE
WIP: make whitened residuals available

### LINKED ISSUE #810: Weighted mean of post-fit residuals is not using scaled uncertainties; affecting chi2 calculation.
When I calculated the weighted mean of post-fit residuals it is ~identically zero when **not** applying EFAC/EQUADs, but presumably these factors should be used when fitting the mean phase, and thus the weighted mean should be zero when using the scaled TOA uncertainties as weights.  I found this using WidebandTOAFitter, but I tried with GLSFitter and it's the same, so I think it's a general issue.  This also affects the chi-squared calculation, since it uses the post-fit residuals; while the chi-squared calculation doesn't require zero-mean, I think this is implied in any set of post-fit timing residuals.

### PR DESCRIPTION
**Pull request by aarchiba**
Go over the calculations of chi-squared and noise residuals so that whitened residuals are routinely available on Residuals objects.

Closes #810 #976

### CODE REVIEW

**Comment by aarchiba** [comment]
I think the existing code has a bug in how we do rank-reduced fits - `phiinv` needs to be rescaled by `norm**2`; that fix is in here, but I can pull it out and file a standalone PR if I'm right. Likewise I can put in a standalone fix for #810.

**Comment by aarchiba** [comment]
> I think the existing code has a bug in how we do rank-reduced fits - `phiinv` needs to be rescaled by `norm**2`; that fix is in here, but I can pull it out and file a standalone PR if I'm right. Likewise I can put in a standalone fix for #810.

In fact it's not a problem because we don't normalize columns corresponding to noise basis functions (or the offset), though I have observed this causing problems. I had to copy this fix over to #1013 to avoid test failures due to numerical issues on the actual NGC6440E data set.

**Comment by paulray** [comment]
Any chance of getting this merged? I'd like to be able to get whitened residuals easily.

**Comment by aarchiba** [comment]
This is a bit of a mess. A more direct approach would be to make `whitened_residuals` a property on residuals objects that used the red noise object that fitters attach to construct whitened residuals. This was trying to clean up the fitters too, and I think now that the code has diverged it might be better to start simpler.

**Comment by abhisrkckl** [comment]
This was implemented in #1671.
So I am closing this.

**Pull request closed without merging**
