### PR TITLE
Raise exception for astropy <4 in __init__.py

### LINKED ISSUE #1354: `import pint` fails when astropy version is less than 4
Here is how to reproduce the issue:

```
>>> import astropy
>>> astropy.version.major=3
>>> import pint
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/home/abhimanyu/anaconda3/envs/pint-devel/lib/python3.9/site-packages/pint_pulsar-0.7+2686.gbfa227ef.dirty-py3.9.egg/pint/__init__.py", line 110, in <module>
     log.warning(
 NameError: name 'log' is not defined
```

### PR DESCRIPTION
**Pull request by dlakaplan**
Fixes #1354 

astropy >=4 is enforced by `requirements.txt`

### CODE REVIEW

**Comment by paulray** [comment]
I guess this is OK, but we've definitely had people install PINT, then upgrade via git pull and never need to run `pip` again so that requirements.txt doesn't get applied. This happened to many of us with loguru, for example.

**Comment by dlakaplan** [comment]
If that's the case, then probably raising an exception is better than emitting a warning.

**Comment by paulray** [comment]
Indeed, especially for something as old as astropy 3.

**Comment by dlakaplan** [comment]
Now astropy < 4 raises an exception, and there is a test for that.

**Pull request merged**
