### PR TITLE
Fix ecliptical coordinate bug

### PR DESCRIPTION
**Pull request by luojing1211**
This is a fix for issue #304. 

* Unittest have not been added. 
@dlakaplan. Can you try it out?

### CODE REVIEW

**Comment by dlakaplan** [comment]
Works for my test.  Thanks.

**Comment by luojing1211** [comment]
Great. I am waitting for @paulray's further comment on the unittest.

**Comment by luojing1211** [comment]
I agree double precision is enough for position and barycentric radio frequency. But I remember the reason why we truncate the tdbld here is numpy linear algebra did not accept the longdouble precision. I was thinking why do we have to do the steps to truncate the data and lose precision.
Do we get some computational speed benefit from using double?

**Comment by scottransom** [comment]
In general, yes.  There is no hardware support for long double, and so those calculations take a lot more time.  That is especially true when you are using linear algebra codes which call libraries (like numpy does) -- they have accelerated versions of libraries for double precision, but not for long double.

And for almost all pulsar timing calculations (excepting mostly those to do with spin frequency and absolute times) long double is not needed.

So in general, I'd say that we want to be using double precision everywhere, unless we know for sure that we need long double.  And not the other way around.

**Comment by luojing1211** [comment]
Ok, we can change it back?

**Comment by scottransom** [comment]
Did you do some test that suggested that that change needed to be made?  If not, then yes, I suggest that you change that back.  (I'm pretty sure that I changed back another change like this that you made in toa.py a month or two ago).

**Comment by luojing1211** [comment]
This is working. Merging.

**Pull request merged**
