### PR TITLE
Add How-to questions from Wiki

### PR DESCRIPTION
**Pull request by aarchiba**
This adds a Howto page to our docs to cover what's currently on https://github.com/nanograv/PINT/wiki/How-To . Additional content from the wiki might should be migrated into the docs. 

The doc page added by the PR is here: https://nanograv-pint--1311.org.readthedocs.build/en/1311/user-questions.html

### CODE REVIEW

**Comment by aarchiba** [comment]
> Perhaps we delete things from the wiki that have been migrated to the official docs, and add a link on the wiki to that docs page. Then we can still add content to the wiki as questions from users come up and are answered.

Yes, that seems quite sensible, and also helps people find where in the docs this kind of question is answered, both for looking things up and for migrating further wiki content in future.

There may be other things on the wiki that should be migrated, I haven't really looked in detail.

**Comment by aarchiba** [comment]
Looking at the longer entries referenced there, https://github.com/nanograv/PINT/wiki/How-To:-Simple-Python-PINT-Tools looks like it should be turned into a tutorial notebook, but that would take work. https://github.com/nanograv/PINT/wiki/How-To:-Common-Timing-Workflow wouldn't be so easy to convert. I'm sort of inclined to migrate them to separate How-to documents; we can point to an example notebook (which would have the advantage of maybe letting us know if we break this stuff!) later.

**Comment by aarchiba** [comment]
How-tos should point to `pint.fitter.Fitter.auto`.

**Comment by aarchiba** [comment]
Edited the wiki to point to the how-tos in the docs.

**Comment by dlakaplan** [comment]
All this looks fine.  Just to note that we should periodically do this (move things from the wiki to rtd).  I can merge if you are done.

**Pull request merged**
