### PR TITLE
Generate Fake TOAs

### PR DESCRIPTION
**Pull request by paulray**
Generating fake TOAs is useful for several things, including making datasets for doing tests.
This PR includes:
* The ability to format TOAs as Tempo2 or Princeton format strings for output to a .tim file
* The ability to init a `TOA()` with an `astropy.Time`
* The ability to apply a vector of time adjustments to a TOA table
* A very simple top level script (currently called `zima.py`, as in fake beer) that generates a set of TOAs for a given frequency, observatory, and cadence, with 0 residual for a specific model, and writes them out as a .tim file.  This could be expanded to do a lot more things, like adding white and red noise and so on.

### CODE REVIEW

**Comment by luojing1211** [comment]
To have a working d_phase_d_toa(), we need your fake toa generator. If this branch is merged I can change d_phase_d_toa() function to the new API.

**Comment by paulray** [comment]
@luojing1211 - What function exactly do you need?  The generation of fake TOAs isn't very well encapsulated in my code.  I should probably wrap it up in a function or something.

**Comment by luojing1211** [comment]
Init a TOA with an astropy Time. By the way, since astropy time can take a list of times, does your function has the ability to take one time array with list of time in it? Or just take a list of astropy time. 

-Luo Jing

**Comment by paulray** [comment]
OK, this code shouldn't hurt anything, so I'm going to merge it.
You can init a `TOA()` with an `astropy.Time` as the MJD argument. Since a `TOA()` can only represent a single TOA, it does not work with a list of times.

**Comment by scottransom** [comment]
Note that we need d_phase_d_toa to get an instantaneous topocentric 
pulsar freq as well.  And the new method/function adjust_TOAs() that 
Paul just input could be perfect for that.

Basically you would make a copy (if necessary) of the TOAs in question, 
and then add known offsets plus and minus the TOA so that you could 
determine a good numeric phase derivative via the .phase() method.

Scott

On 02/15/2016 11:20 AM, Jing Luo wrote:
> To have a working d_phase_d_toa(), we need your fake toa generator. If
> this branch is merged I can change d_phase_d_toa() function to the new API.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nanograv/PINT/pull/106#issuecomment-184278840>.Web
> Bug from
> https://github.com/notifications/beacon/AAIHIsn8C_K6ie0igOynmHahbIUj9owXks5pkfJlgaJpZM4Had_T.gif
>

-- 
Scott M. Ransom            Address:  NRAO
Phone:  (434) 296-0320               520 Edgemont Rd.
email:  sransom@nrao.edu             Charlottesville, VA 22903 USA
GPG Fingerprint: 06A9 9553 78BE 16DB 407B  FFCA 9BFA B6FF FFD3 2989

**Pull request merged**
