### PR TITLE
START/FINISH Updated and Displayed

### PR DESCRIPTION
**Pull request by champagne-cmd**
The `START` and `FINISH` parameters in the .par files are now incorporated as frozen `MJDParameters`, displayed in .par file output, and updated after fitting.

### CODE REVIEW

**Comment by paulray** [comment]
Do you also need to remove START and FINISH from ignore_params?
Also, if you have time to add a unit test that show that they get updated that would be great!

**Comment by paulray** [comment]
Oh, and please add a line to CHANGELOG

**Comment by champagne-cmd** [comment]
I think they still need to be in `ignore_params` so that they register as "interesting lines" like `UNITS` and `EPHVER` and are addressed in `read_parfile` in the same fashion. I will add the test and modify the CHANGELOG.

**Comment by paulray** [comment]
Oops, I see a couple of tests failed.  Probably small issues.  You can run them on your local machine one at a time with `pytest -s -v tests/test_fitter.py`, for example.  The "-s" makes in print out stdout and "-v" makes it more verbose about what test it is running.

**Pull request merged**
