### PR TITLE
remove redundant cmd line args in compare_parfiles.py

### PR DESCRIPTION
**Pull request by abhisrkckl**
see #1445

### CODE REVIEW

**Comment by dlakaplan** [comment]
I'm less sure that this is needed.  Without knowing what the default behavior is, it can be useful to be able to explicitly specify what you want to happen.

**Comment by abhisrkckl** [comment]
If neither `--convertcoordinates` nor `--no-convertcoordinates` is provided, the behavior of the script is equivalent to `--convertcoordinates`.

**Comment by abhisrkckl** [comment]
So aren't `--convertcoordinates` and `--no-dmx` redundant?

**Comment by dlakaplan** [comment]
My point is that a user may not want to remember which behavior is default, so being able to specify explicitly on the command line can be useful if it doesn't otherwise hurt things.

**Comment by abhisrkckl** [comment]
Ah... that makes sense. I'll close this issue and add the new tests to PR #1444.

**Pull request closed without merging**
