### PR TITLE
Added MeerKAT as an observatory

### PR DESCRIPTION
**Pull request by scottransom**
This uses the TEMPO2 MeerKAT clock correction files (which can be obtained here:  https://archive-gw-1.kat.ac.za/public/tfr/mk2utc.clk )

### CODE REVIEW

**Comment by scottransom** [comment]
yeah, I think that is correct about the GPS correction (and it looks like that is happening already).  I can add a test, but aren't we not using tests that require TEMPO2?

**Comment by aarchiba** [comment]
We have a few tests that compare our results to stored results previously output by tempo2 - so a simple test would be to have tempo2 barycenter a TOA or two from MeerKAT, store those in a file, then barycenter them ourselves and compare.

**Comment by scottransom** [comment]
This should be ready to go now, I think.

**Comment by paulray** [comment]
Looks good, but your test needs blackening. Note that in VS Code you can set it to run blacken on save. You can also add a pre-commit hook to check blackening before you push.

**Comment by scottransom** [comment]
I actually don't want VS code to blacken on save....  just when I'm working on PINT!  And I had *just* blacked it, but forgot and tweaked the "TEMPO2" line and screwed it up!  D'oh!  PEBKAC (and stupid black rules).

**Comment by paulray** [comment]
Note that "editor.formatOnSave" is a per-project setting. It lives in my .vscode/settings.json in the PINT tree. So it won't try to blacken my other projects.

**Comment by scottransom** [comment]
Cool.  I just put that editor.formatOnSave setting on for PINT alone.  That's cool!  I didn't know you could do that.  Thanks, @paulray !

**Pull request merged**
