### PR TITLE
Event_optimize results.txt bug fix

### PR DESCRIPTION
**Pull request by devbhakt**
A fix for issue #1811.

This saves the median ranges calculated post MCMC run as a variable to be called again in order to write them into the results.txt file

### CODE REVIEW

**Comment by abhisrkckl** [comment]
Can you post an example of how this looks in the output file?

**Comment by devbhakt** [comment]
Here are the two output files:
Current version:

Post-MCMC values (50th percentile +/- (16th/84th percentile):

Maximum likelihood par file:
# Created: 2024-07-30T10:25:34.041166
# PINT_version: 1.0.1+60.g0145fab2
# User: Deven Bhakta (drb7tg)
# Host: drb7tg-framework
# OS: Linux-6.5.0-1025-oem-x86_64-with-glibc2.35
# Python: 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0]
# Format: pint
PSRJ                           J0030+0451
UNITS                                 TDB
DILATEFREQ                              N
DMDATA                                  N
NTOA                                    0
RAJ                      0:30:27.43030000
DECJ                     4:51:39.74000000
PMRA                                 -5.3
PMDEC                                -2.0
PX                                    0.0
POSEPOCH           52079.0000000000000000
F0                  205.53069927477466194 1 1.1251330533923464827e-08
F1              -4.3083152366187108594e-16 1 9.898089838894459467e-19
PEPOCH             50984.4000000000000000
TZRMJD             56000.0000000000000000
TZRSITE                                 1
TZRFRQ                             1400.0
PLANET_SHAPIRO                          N
DM                                  4.333


Here is the updated version:

Post-MCMC values (50th percentile +/- (16th/84th percentile):
F0      :          205.530699274541 (+   1.2412e-10 / -   1.1449e-08)
F1      :     -4.29780339222501e-16 (+   2.1083e-19 / -   5.3914e-20)
PHASE   :         0.513638108470009 (+    0.0014756 / -    0.0083949)

Maximum likelihood par file:
# Created: 2024-07-30T10:27:17.914198
# PINT_version: 1.0.1+61.g0f07e48d
# User: Deven Bhakta (drb7tg)
# Host: drb7tg-framework
# OS: Linux-6.5.0-1025-oem-x86_64-with-glibc2.35
# Python: 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0]
# Format: pint
PSRJ                           J0030+0451
UNITS                                 TDB
DILATEFREQ                              N
DMDATA                                  N
NTOA                                    0
RAJ                      0:30:27.43030000
DECJ                     4:51:39.74000000
PMRA                                 -5.3
PMDEC                                -2.0
PX                                    0.0
POSEPOCH           52079.0000000000000000
F0                   205.5306992744677359 1 2.981482793984466917e-10
F1              -4.2998965661926157375e-16 1 2.6485076505706956507e-19
PEPOCH             50984.4000000000000000
PLANET_SHAPIRO                          N
DM                                  4.333
TZRMJD             56000.0000000000000000
TZRSITE                                 1
TZRFRQ                             1400.0

**Comment by abhisrkckl** [comment]
Is this change covered by a test? Unfortunately, codecov isn't working so I can't tell.

**Comment by abhisrkckl** [comment]
I'll merge this if this is ready.

**Comment by abhisrkckl** [comment]
Please add a CHANGELOG entry

**Pull request merged**
