### PR TITLE
New tutorial for simulating data and making a mass-mass plot

### PR DESCRIPTION
**Pull request by dlakaplan**
Nothing too fancy.  Uses `pint.toa.make_fake_toas` to simulate data for PSR B1534+12 using the par file from Fonseca et al. (2014).  And then various utilities to get the post-Keplerian constraints.

So it's not quite the same (no intensive Shapiro delay campaigns, etc).  But still results in a nice plot.

### CODE REVIEW

**Comment by aarchiba** [comment]
This is great! I wonder if we should make the section "Tutorials" into "Tutorials and examples"? Then Tutorials would be actual pedagogical tutorials, and Examples would be miscellaneous cool things not necessarily focused on teaching readers?

**Comment by aarchiba** [comment]
I notice you had to change the par file so filed #1097 and #1098.

**Comment by aarchiba** [comment]
I think some of the formatting is mangled - notebook text areas are Markdown and support $\dot f$-style math (with dollar signs), and I *think* those are correctly translated by Sphinx.

**Comment by dlakaplan** [comment]
Yes, in the readthedocs build the formatting is weird.  Not sure if this is the same inconsistency we've been seeing elsewhere.  But the notebook itself renders fine.  I could remove the math, or wait and see how this appears on the full build.

**Comment by aarchiba** [comment]
If it's okay in the notebook, then it *should* be okay in local doc builds, and it *should* be okay in readthedocs (which is the one that matters most, realistically). I'm doing a local build to try to see what happens locally; if that's different from readthedocs I'll see if I can figure out why.

**Comment by aarchiba** [comment]
Yeah it's fine locally but broken on readthedocs.

**Comment by aarchiba** [comment]
Hooray coverage works! But is completely unhelpful here as we don't collect coverage information from the notebook runs.

**Pull request merged**
