### PR TITLE
Fixed wsrt observatory to use Tempo2 clock files

### PR DESCRIPTION
**Pull request by paulray**
Also fixed Tempo2 clock file reader to be more robust

### CODE REVIEW

**Comment by paulray** [comment]
Should add a test, but I don't want to make travis depend on having Tempo2 installed.

**Comment by rossjjennings** [comment]
For a test, maybe you could just add a clock file that might cause problems to `tests/datafile` and test reading it in?

**Comment by paulray** [comment]
Good idea @rossjjennings. Done.

**Comment by paulray** [comment]
Note that to successfully use WSRT with PINT, you will need to pull the latest Tempo2, since I had to patch the $TEMPO2/clock/wsrt2gps.clk file as it had a couple of lines with just "0" on them, which broke PINT's parser.

**Comment by paulray** [comment]
I'm done with this and is passes all tests.  Is it OK to merge?

**Pull request merged**
