### PR TITLE
Event optimize update errors

### PR DESCRIPTION
**Pull request by devbhakt**
Addresses issue #1529 where event optimize is not updating the errors in the post fit par file. This calculates an error for each parameter from the 68% confidence interval and updates the model within the fitter.

### CODE REVIEW

**Comment by abhisrkckl** [comment]
Is this ready to go?

**Comment by devbhakt** [comment]
Yes, this is ready to go.

**Comment by abhisrkckl** [comment]
Can you add a CHANGELOG entry?

**Comment by devbhakt** [comment]
Changelog entry has been added!

**Pull request merged**
