### PR TITLE
New model builder

### PR DESCRIPTION
**Pull request by luojing1211**
Hi all, 

I have changed model builder. Please take a look and leave your comments. 

Thanks. 

-Luo Jing

### CODE REVIEW

**Comment by vhaasteren** [comment]
This is indeed the design I also had in mind, and it works for me (after some edits). A couple of comments:

- You need to merge upstream, there have been other commits
- Add model_builder to the setup.py as a module
- The examples section of your model_builder docstring needs to be updated.
- I like the __str__ functionality of model_builder, but at the moment it throws an error
- It'd be great to have a helper function that does all this in one go. At the moment, to read a parfile, I need to do:

import pint.models.model_builder as mb
mc = mb.model_builder("J0613", parfile="J0613.par")
J0613_model = mc.build_model()
model_obj = J0613_model()
model_obj.read_parfile("J0613.par")

It has to be this way, of course, but there could be a helper function that does all this at once.

Good work!

**Comment by luojing1211** [comment]
On Sat, Jul 4, 2015 at 5:27 PM, Rutger <notifications@github.com> wrote:

> This is indeed the design I also had in mind, and it works for me (after
> some edits). A couple of comments:
>
>    - You need to merge upstream, there have been other commits
>
> ​Done​


>
>    - Add model_builder to the setup.py as a module
>
> ​Done​


>
>    - The examples section of your model_builder docstring needs to be
>    updated.
>
> ​Updated​


>
>    - I like the *str* functionality of model_builder, but at the moment
>    it throws an error
>
> ​Fixed​


>
>    - It'd be great to have a helper function that does all this in one
>    go. At the moment, to read a parfile, I need to do:
>
> ​For the case with parfile:
​
import pint.models.model_builder as mb
mc = mb.model_builder("J0613", parfile="J0613.par")
​mJ0613 = mc.model_instance​

​Can I add a function that return mode_instance directly. For example:
mJ0613 = ​mb.model_builder("J0613", parfile="J0613.par")
and mJ0613 is a model instance that with parfile read in.

**Comment by vhaasteren** [comment]
Hi Jing,

I think a few minor tweaks are necessary before a merge, all related to this example in the docstring:

        Read model from parfile :
        mc = model_constructor("PulsarJ1955", parfile ="J1955.par" )
        psrJ1955 = mc.model_instance

# Comment 1 #
Firstly, model_constructor is actually called model_builder. So that should be changed. Also, from a usability perspective, it would be preferable to be able to call a function or class that directly returns the model instance. So your example would be:

        psrJ1955 = model_yournamehere("PulsarJ1955", parfile ="J1955.par")

Right now it is two lines, whereas if you give the class a parfile, most likely the user is not interested in the model_constructor object. The user wants the model instance. Since there is no difference in calling a function, or initializing a class, perhaps you can just add this function to the model_builder.py (untested):

def get_model(name, parfile):
    mb = model_builder(name, parfile)
    return mb.model_instance

I called it get_model, because we already obtain the toas by calling get_TOAs(timfile).

# Comment 2 #
MyModer should be MyModel

# Comment 3 # 
Similar to my comment one. If we manually build a model, we now have to do:

    mb = pm.model_builder("BT_model")
    mb.add_components(BT)
    model = mb.build_model()
    MyModel = model()
    MyModel.read_parfile(parfile)

I think this can be cut down to three lines, if we provide a function to the model_builder that does this:

psrBTmodel = mb.read_parfile(parfile)

which combines the last three lines. So don't remove any functionality, just add this extra functionality.

**Comment by vhaasteren** [comment]
Hi Jing,

I gave some extra comments regarding the model builder. If you can have a
look at those, we can merge them in afterward. Thanks!

Rutger

On Sun, Jul 5, 2015 at 12:16 PM, luojing1211 <notifications@github.com>
wrote:

> On Sat, Jul 4, 2015 at 5:27 PM, Rutger <notifications@github.com> wrote:
>
> > This is indeed the design I also had in mind, and it works for me (after
> > some edits). A couple of comments:
> >
> > - You need to merge upstream, there have been other commits
> >
> > ​Done​
>
>
> >
> > - Add model_builder to the setup.py as a module
> >
> > ​Done​
>
>
> >
> > - The examples section of your model_builder docstring needs to be
> > updated.
> >
> > ​Updated​
>
>
> >
> > - I like the *str* functionality of model_builder, but at the moment
> > it throws an error
> >
> > ​Fixed​
>
>
> >
> > - It'd be great to have a helper function that does all this in one
> > go. At the moment, to read a parfile, I need to do:
> >
> > ​For the case with parfile:
> ​
> import pint.models.model_builder as mb
> mc = mb.model_builder("J0613", parfile="J0613.par")
> ​mJ0613 = mc.model_instance​
>
> ​Can I add a function that return mode_instance directly. For example:
> mJ0613 = ​mb.model_builder("J0613", parfile="J0613.par")
> and mJ0613 is a model instance that with parfile read in.
>
>
> >
> > import pint.models.model_builder as mb
> > mc = mb.model_builder("J0613", parfile="J0613.par")
> > J0613_model = mc.build_model()
> > model_obj = J0613_model()
> > model_obj.read_parfile("J0613.par")
> >
> > It has to be this way, of course, but there could be a helper function
> > that does all this at once.
> >
> > Good work!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nanograv/PINT/pull/41#issuecomment-118560540>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nanograv/PINT/pull/41#issuecomment-118653198>.
>



-- 

______________________________________________________________________
 dr. Rutger van Haasteren, Einstein postdoctoral fellow
 Jet Propulsion Laboratory, Pasadena, USA
 E-mail: vhaasteren@gmail.com

**Comment by vhaasteren** [comment]
I have merged this branch, and made a few extra changes that allow loading a parfile with:

    import pint.models as models
    m = models.get_model('examples/NGC6440E.par')

This is just like loading timfiles. Note that I have removed the option to name your model when using get_model. If we are not in control of the timing model object anyway, the basename of the filename should suffice.

**Pull request merged**
