### PR TITLE
Feature photonphase polycos

### PR DESCRIPTION
**Pull request by sashalvna**
A polycos argument has been added to photonphase.py, which uses polycos to calculate pulse phases without using the full model of the pulsar. Useful for large files, where photonphase.py previously used to crash/time out. A test of the polycos argument has also been added to test_photonphase.py.

### CODE REVIEW

**Comment by paulray** [comment]
What you might do is make a new branch and make sure it is fully up to date with the current nanograv/master, then just commit your changes to `photonphase.py` and `test_photonphase.py`?

**Comment by paulray** [comment]
Also, the B1509 datafile already exists in `tests/datafile`, so should not be included in your PR.

**Comment by scottransom** [comment]
The way that you would normally handle accounting for new changes to the repo is simply to rebase your branch on PINT master.

**Comment by paulray** [comment]
> The way that you would normally handle accounting for new changes to the repo is simply to rebase your branch on PINT master.

But, in this case it looks like the commits in the PR revert desired changes in PINT, like using  `logging` instead of `astropy.log`.  So, it seems like git rebase won't have the desired effect.

**Pull request closed without merging**
