### PR TITLE
Verbosity fix

### PR DESCRIPTION
**Pull request by almcewen0**
per issue https://github.com/nanograv/PINT/issues/984, I have adjusted the verbosity of a few of the components. This includes:
1. changing language when components are boolean
2. reducing log level from WARNING to INFO for START/FINISH/CHI2/NTOA
3. including these logger statements only when in "max" verbosity level 

If there are other parameters that should be reported less/more often, or if there are parameters that would be better suited for different INFO/WARNING language, please comment those parameters and changes here.

### CODE REVIEW

**Comment by paulray** [comment]
Did this get merged, or just closed without merging?

**Comment by almcewen0** [comment]
> Did this get merged, or just closed without merging?

i closed it, because it looked like some of my "compare fix" got tangled up in this branch. so I thought I would wait until the other PR gets merged.

**Comment by paulray** [comment]
Can I merge that now?

**Comment by almcewen0** [comment]
yes, i think so.

**Pull request closed without merging**
