### PR TITLE
Jump_flags_to_params Fix

### PR DESCRIPTION
**Pull request by champagne-cmd**
Updated `jump_flags_to_params` and fixed logic errors in the function. I also added a test for it and updated how jumps were read in from the .tim file in `toa.py` to match the new way TOAs store jumps (in a list to allow for multiple jumps/TOA).

### CODE REVIEW

**Comment by scottransom** [comment]
@champagne-cmd When I try to use this with pair'd sets of JUMPs in an input .tim file (exactly the file that I sent you with the MeerKAT TOAs), I'm getting an error.  This seems to do with the fact that you are using list values (i.e. [1]) as the JUMP identifiers now?  Why is that?

```
Traceback (most recent call last):
  File "/home/sransom/python_venvs/py3/bin/pintk", line 33, in <module>
    sys.exit(load_entry_point('pint-pulsar', 'console_scripts', 'pintk')())
  File "/home/sransom/git/PINT/src/pint/scripts/pintk.py", line 164, in main
    app = PINTk(root, parfile=args.parfile, timfile=args.timfile, ephem=args.ephem)
  File "/home/sransom/git/PINT/src/pint/scripts/pintk.py", line 41, in __init__
    self.openPulsar(parfile=parfile, timfile=timfile, ephem=ephem)
  File "/home/sransom/git/PINT/src/pint/scripts/pintk.py", line 111, in openPulsar
    self.widgets["plk"].setPulsar(
  File "/home/sransom/git/PINT/src/pint/pintk/plk.py", line 556, in setPulsar
    self.updateJumped(getattr(self.psr.prefit_model, param).name)
  File "/home/sransom/git/PINT/src/pint/pintk/plk.py", line 1092, in updateJumped
    for jump_num in [
  File "/home/sransom/git/PINT/src/pint/pintk/plk.py", line 1093, in <listcomp>
    int(dict["jump"]) if "jump" in dict.keys() else np.nan
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```

**Comment by champagne-cmd** [comment]
That looks like it is because the code isn’t updated with my other PR,
restructuring .par jumps. I’m sorry I should have mentioned that, this PR
was to synchronize this function with the new jump implementation and fix
the logic errors that were present. Merging the other PR should fix that.
They are lists to allow one TOA to have multiple jump flags.

On Wed, Mar 17, 2021 at 2:58 PM Scott Ransom ***@***.***>
wrote:

> @champagne-cmd
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchampagne-cmd&data=04%7C01%7Cchloe.a.champagne%40mail-service-3-mx.vanderbilt.edu%7C0a1092e681644115624d08d8e97ef09b%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637516078692583962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lb4WUI%2BWQe%2FNMUOjz7RHGYKfxRF59pwCSaOc7N%2FxO10%3D&reserved=0>
> When I try to use this with pair'd sets of JUMPs in an input .tim file
> (exactly the file that I sent you with the MeerKAT TOAs), I'm getting an
> error. This seems to do with the fact that you are using list values (i.e.
> [1]) as the JUMP identifiers now? Why is that?
>
> Traceback (most recent call last):
>   File "/home/sransom/python_venvs/py3/bin/pintk", line 33, in <module>
>     sys.exit(load_entry_point('pint-pulsar', 'console_scripts', 'pintk')())
>   File "/home/sransom/git/PINT/src/pint/scripts/pintk.py", line 164, in main
>     app = PINTk(root, parfile=args.parfile, timfile=args.timfile, ephem=args.ephem)
>   File "/home/sransom/git/PINT/src/pint/scripts/pintk.py", line 41, in __init__
>     self.openPulsar(parfile=parfile, timfile=timfile, ephem=ephem)
>   File "/home/sransom/git/PINT/src/pint/scripts/pintk.py", line 111, in openPulsar
>     self.widgets["plk"].setPulsar(
>   File "/home/sransom/git/PINT/src/pint/pintk/plk.py", line 556, in setPulsar
>     self.updateJumped(getattr(self.psr.prefit_model, param).name)
>   File "/home/sransom/git/PINT/src/pint/pintk/plk.py", line 1092, in updateJumped
>     for jump_num in [
>   File "/home/sransom/git/PINT/src/pint/pintk/plk.py", line 1093, in <listcomp>
>     int(dict["jump"]) if "jump" in dict.keys() else np.nan
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnanograv%2FPINT%2Fpull%2F1007%23issuecomment-801381293&data=04%7C01%7Cchloe.a.champagne%40mail-service-3-mx.vanderbilt.edu%7C0a1092e681644115624d08d8e97ef09b%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637516078692583962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Was7caSY5lrxub%2FBICH9ak7XaG2K2opbqqH%2FVvEmf%2B8%3D&reserved=0>,
> or unsubscribe
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANAU7OWBTC23YQ2YCPRQKH3TEECTXANCNFSM4ZDB43JA&data=04%7C01%7Cchloe.a.champagne%40mail-service-3-mx.vanderbilt.edu%7C0a1092e681644115624d08d8e97ef09b%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637516078692593961%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=K9jq2oD3UTgoiWYUFttLZ1mmhZrQxPcEbMlfXOpWOqg%3D&reserved=0>
> .
>
-- 
Sincerely,
Chloe Champagne
Computer Engineering and Applied Math
Vanderbilt University, Class of 2022

**Comment by champagne-cmd** [comment]
files used to test:
[M28N.zip](https://github.com/nanograv/PINT/files/6198919/M28N.zip)

**Comment by scottransom** [comment]
@champagne-cmd So I merged this today, but it doesn't seem to be working still.  Which other PR about JUMPs did you mean from above?

The problem I'm seeing now, is that if there are JUMPs in the .tim file that get turned into model params, their key_index ends up being a list with the *string* of a number rather than the number of the jump itself.  That means that the select_toa_mask() method (in parameter.py) can't find the TOAs that go with the JUMP.

**Pull request merged**
