### PR TITLE
Fix der test

### PR DESCRIPTION
**Pull request by luojing1211**
This is a simple fix for the current derivative failure.

### CODE REVIEW

**Comment by luojing1211** [comment]
The tox failing is due to astropy4.0 changes. The only thing I changed it the numerical derivative step size. I think this should get merged and then fix astropy 4.0 issue. What do you think @scottransom @paulray @demorest

**Comment by paulray** [comment]
We don't yet support astropy 4.0. See #550 
So, can you change requirements.txt to say astropy<4.0 in this PR?

**Comment by luojing1211** [comment]
I don't know why tox somehow uses astropy 4.0.  PR #594 is aiming to fix the astropy 4.0 issue.

**Comment by paulray** [comment]
Yeah, I can't figure out why tox is installing astropy 4.0.  The requirements_dev.txt clearly specifies astropy<4.0.  I think @aarchiba made the tox test in travis. Anne, any ideas?

**Comment by luojing1211** [comment]
@paulray if you think this PR is ok, I will just merge it. TOX is really another issue.

**Comment by paulray** [comment]
Yeah, that is fine, but it won't fix the main branch test failures, which was the point.

**Comment by luojing1211** [comment]
OK, I will fix that separately.

**Pull request merged**
