### PR TITLE
Whitened residuals in `pintk`

### PR DESCRIPTION
**Pull request by abhisrkckl**
image

### CODE REVIEW

**Comment by dlakaplan** [comment]
This looks good.  My only question is if it's worth reordering the axis options. So that e.g., `WB DM res` and `white-res` are at the top near `pre-fit` and `post-fit`, and `WB DM err` is near `TOA error`.  I don't think this matters too much either way but it could make things more clear for some users.

**Comment by dlakaplan** [comment]
Also needs CHANGELOG

**Comment by abhisrkckl** [comment]
Reordered the axes.
image

**Comment by dlakaplan** [comment]
great.  I can merge if you are done (and I can merge the other PR first if you'd prefer).

**Comment by abhisrkckl** [comment]
I'm done. This can be merged first.

**Pull request merged**
