### PR TITLE
Toa selection optimize

### PR DESCRIPTION
**Pull request by luojing1211**
I update the toa selection class for JUMPS and DMX. 
It speeds the processing speed (including fitting) several times. 
Features: 
* Generalized TOA select class, can be applied at JUMPS and DMX or their toa selection method. 
* Add a mini cache in the class with the option of hash input. 
* fix a bug in the fitter.

### CODE REVIEW

**Comment by luojing1211** [comment]
Hi all, this branch has unittest and passed it. @all anyone wanna to check it out?

**Comment by luojing1211** [comment]
Hi @scottransom @paulray @demorest do you want to try this branch out or give some more tests? This optimization reduces 25% of computational time when doing a full parameter fitting one iteration.

**Comment by paulray** [comment]
@luojing1211, I merged the other pull requests but now there are conflicts on this one. Can you resolve?

**Comment by luojing1211** [comment]
This branch can be merged. Merging

**Pull request merged**
