### PR TITLE
Making script verbosity easier to control

### PR DESCRIPTION
**Pull request by dlakaplan**
Addresses #1377

Separately, we might want to check which executables/scripts are still needed.  I didn't update all of them since some don't seem to be used.

### CODE REVIEW

**Comment by paulray** [comment]
Looks good to me! Are the only excluded scripts the 2 alternatives to event_optimize.py? I'm not really sure what those are.

**Comment by dlakaplan** [comment]
I updated the recipe for how to do this in:
https://nanograv-pint--1380.org.readthedocs.build/en/1380/_autosummary/pint.logging.html
and 
https://nanograv-pint--1380.org.readthedocs.build/en/1380/_autosummary/pint.logging.get_level.html#pint.logging.get_level

**Comment by dlakaplan** [comment]
Both done.  `pintbary` has a number of print statements which is probably why I didn't update it before.

**Comment by paulray** [comment]
Great! I think this can be merged once tests pass

**Pull request merged**
