### PR TITLE
Fix parse parameter line

### PR DESCRIPTION
**Pull request by luojing1211**
This is a fix for the unct did not assigned error when parsing a par file line like: F3 0 0

### CODE REVIEW

**Comment by paulray** [comment]
Thanks for this fix!

I just looked at this page of the Tempo2 docs: http://www.atnf.csiro.au/research/pulsar/tempo2/index.php?n=Documentation.Parameters

It gives three ways parameters can be specified:
```
In more detail, a pulsar which has a spin period of P0=1.23456 s and no fitting is required then use:
 P0 1.23456 
To request that tempo2 fits for this parameter:
 P0 1.23456 1
or to include an uncertainty on the measurement (which is ignored by the main tempo2 software)
 P0 1.23456 1 0.00003
```
Notice that it does *not* say there is a form where the uncertainty is specified without having fit_flag present.

However, in their example J0437 par file on the same page, they have this line:
```
 OMDOT           0.016                     1.000e-02 
```

How is that distinguished from:
```
OMDOT 0.016 0
```
or
```
OMDOT 0.016 1
```

I fear that it may check to see if that third value is an integer or not.  This is not a great way of doing things.  What should PINT do? @demorest @scottransom

**Comment by paulray** [comment]
Just a note that this addresses Issue #211

**Comment by luojing1211** [comment]
How about to have the ability to read the line like : 
```
 OMDOT           0.016                     1.000e-02 
```
And force user to have an no-integer for uncertainty. Or more specifically no "1" and "0"  in the uncertainty.

**Comment by luojing1211** [comment]
Now the fit_flag is set to only accept 0 and 1, otherwise, it will be treated as uncertainty.

**Comment by luojing1211** [comment]
As the discussed in the meeting. This branch is ready to merge. Does anyone have more question? I will merge it at 5:00pm CST, if no one has questions and no one merge it before that.

**Pull request merged**
