### PR TITLE
Move parameter validations from setup() to validate()

### PR DESCRIPTION
**Pull request by luojing1211**
This PR moves the parameter validation from setup() to validate(). This will allow us to set up the timing model first (e.g., register derivatives), without error raise and then validate the parameters. 
One can do
``` 
tm = TimingModel('name',  [Astrometry(), Spindown()])
tm.setup() # setup the derivatives. In old method, this would fail since 'RA' and 'Dec' are not set.
tm.RA.value = '19:59:48'
tm.DEC.value = '20:48:36'
tm.F0.value = 1.6 * u.ms  
tm.validate() # Check parameters.
```
Or
```
tm = get_model('pulsar.par', validate=False)
tm.add_component(Jump())
tm.setup() # This would fail in the old setup()
tm.JUMP1.value = 0.3
tm.validate()
```

### CODE REVIEW

**Comment by paulray** [comment]
Should this or #585 be reviewed first? Is there a way to merge them into a single PR? It seems like they are tightly related.

**Comment by paulray** [comment]
Why do a couple of the classes call super.validate() but the rest don't?  Is there something different about the ones that call validate on their superclass?

**Comment by luojing1211** [comment]
PR #585 should be merged after this one. I thought about putting them into on PR, however, they are not totally related, and it is easier for me to run the tests. 

About the super().validate comments, some component is inherited from a base component which has validation function. That is why it is necessary to run super().validate. But I can add them to all of the components.

**Comment by paulray** [comment]
Add .is_valid attribute to a timing model so you can check if it has been validated.
Also, have model.phase() verify is_valid before running

**Comment by luojing1211** [comment]
As discussed in the telecon, I added validate() to all components. this can be merged.

**Pull request merged**
