### PR TITLE
Fix DDS CI failures

### PR DESCRIPTION
**Pull request by dlakaplan**
Address #1548

### CODE REVIEW

**Comment by dlakaplan** [comment]
@paulray : this passed CI.  It uses a single random seed so hopefully if it passes once given a version it should keep passing.  does this pass for you locally?

**Comment by paulray** [comment]
This passes on my local Mac

**Comment by paulray** [comment]
Was the issue just randomness? Or did the some version change in astropy/scipy/numpy cause it to be more likely to fail?

**Comment by dlakaplan** [comment]
I don't really know - I wasn't able to reproduce it.

**Pull request merged**
