### PR TITLE
Fix polycos

### PR DESCRIPTION
**Pull request by paulray**
The calls to model.phase in the polyco computation were missing abs_phase=True, so this add that.

### CODE REVIEW

**Comment by paulray** [comment]
Oops, this accidentally includes the edit from #1112

**Comment by aarchiba** [comment]
Can you include a test that shows what was going wrong when `abs_phase` wasn't being passed? Like, what happened? Can you write a test that shows it happening and that it was wrong?

**Comment by paulray** [comment]
I think this is fine. The `test_polycos.py` is updated in this PR as well. It now ensures that phases computed with polycos match phases computed with `model.phase(ts,abs_phase=True)`, rather than `model.phase(ts,abs_phase=False)` which was giving meaningless absolute phases.

**Comment by aarchiba** [comment]
I see, thanks!

**Pull request merged**
