### PR TITLE
Save covariance and correlation matrices in fitter classes

### PR DESCRIPTION
**Pull request by rossjjennings**
This makes parameter covariance and correlation matrices accessible as the `covariance_matrix` and `correlation_matrix` attributes, respectively, of `WLSFitter` and `GLSFitter` instances, once the fit has been run. For `WLSFitter`, this functionality already existed, but the matrices were labelled incorrectly (#625). For `GLSFitter`, the matrices were computed inside the fitting function but not accessible from outside (#542).

### CODE REVIEW

**Comment by paulray** [comment]
Since this affects random_models, @clp3ef and @scottransom should have a look.

**Comment by rossjjennings** [comment]
I discussed this change with @scottransom at the meeting. It's intended to pave the way for @brentshapiroalbert to add his dmxparse code.

**Comment by paulray** [comment]
Cool. Then I'll let Scott merge it.

**Comment by scottransom** [comment]
Thanks, @rossjjennings !  Sorry it took me so long to merge it!

**Pull request merged**
