### PR TITLE
Clean-up covariance matrix pretty-printing.

### PR DESCRIPTION
**Pull request by scottransom**
Removed multiply-reproduced code. 
Add color option for correlation matrix (use it in pintk).
Minor pintk improvements (updating fit info in output parfiles).

An example of the colorized correlation matrix is below.  (There is one more level, for |val| > 0.999, which is red background with white text).

image

### CODE REVIEW

**Comment by dlakaplan** [comment]
The results look pretty nice here, but is there a way to put the color definitions somewhat more understandable/editable?  Maybe just a dictionary at the top of the file, or we could even have a config file (probably not).  And some help in understanding/changing the values since the syntax isn't obvious?

**Comment by scottransom** [comment]
Moving the definitions is easy.  But unless you want another dependency (which might be OK), then the color settings are *incredibly* opaque.  Especially since different terminals (and their default color selections) can change some of the colors.  For example, the code that I chose for correlation values from 0.5-0.9 was *supposed* to be yellow.  But my terminal treats it as that blue.  The orange and red colors *did* come out as planned.  So I'm not sure how to make it easily changeable for people *and* easy to understand what color you are actually going to get.  I suppose we could include a "color test" script that shows all the colors that your terminal produces and the codes.  There are multiple examples of that online.  Or maybe we could just point to one of those in the code and/or docs?  (Note:  I *really* like the improved correlation matrix formatting, though.

Here is a code snippet that prints all the options:
```
def print_format_table():
    """
    prints table of formatted text format options
    """
    for style in range(8):
        for fg in range(30,38):
            s1 = ''
            for bg in range(40,48):
                format = ';'.join([str(style), str(fg), str(bg)])
                s1 += '\x1b[%sm %s \x1b[0m' % (format, format)
            print(s1)
        print('\n')

print_format_table()
```

**Comment by dlakaplan** [comment]
Maybe just move that up top and include the snippet you suggest in a docstring so that it will be available in rtd?

Probably environment variables are also too complicated for this, but I worry about people with unusual terminal setups and/or colorblindness.  I guess that not being able to see distinctions between the different colors wouldn't be as big a problem as bad contrast between the text & background.  And they can always turn off colors entirely.

**Comment by dlakaplan** [comment]
Or just put that in the how-to (which we may need to organize a bit).

**Comment by scottransom** [comment]
@dlakaplan OK.  So I added 2 functions to pint.utils.  A `colorize()` one that can change foreground, background, and text type (i.e. bold, normal, underline...), as well as a `print_color_examples()` utility.  I think those should get picked up by Sphinx.  And I'm using those in the correlation matrix pretty-printing.  For colors, I changed to using "normal", green, yellow, red, and inverse-red, as they apparently work in all terminals (terminals apparently determine which of the 16 base colors work in their terminals and set those appropriately.  The `colorize()` routine only uses those colors, even though many terminals support 256 colors.

**Comment by dlakaplan** [comment]
I think if you change:
```
`colorize()` 
```
to
```
:func:`~pint.utils.colorize`
```
it will link better.  I also don't know if you should put in a reverse link from `colorize` to `print_color_examples`?

Finally, will this work with both standard strings and unicode?

**Comment by scottransom** [comment]
I just checked and yes, it works perfectly with unicode strings as well.  I'll update the doscstrings for that (and with better cross links).

**Comment by dlakaplan** [comment]
Great - that `colorize` function could be nice elsewhere!

**Comment by dlakaplan** [comment]
Looks good to me.  I can merge when you are happy.

**Comment by scottransom** [comment]
I'd say merge away.  I'm happy.

**Comment by dlakaplan** [comment]
ok, will just wait for the checks to finish

**Pull request merged**
