### PR TITLE
Bug fixes and tweaks.

### PR DESCRIPTION
**Pull request by kerrm**
Add some new capabilities for NICER, and fix some small bugs I found along the way.

The units in d_phase_d_toa could be done more gracefully.  I tried putting the correct units in the sample step, but apparently astropy isn't smart enough to figure out cycle/s == Hz, so I just kluged in Hz.

### CODE REVIEW

**Comment by kerrm** [comment]
Looks like it will require some updates to a few other scripts (zima) to reflect the changed units.

**Comment by paulray** [comment]
Do we need to have a discussion of whether phases should be unitless or have units of "cycles"? @luojing1211 what do you think?

**Comment by kerrm** [comment]
It's somewhat ancillary to this question -- regardless of whether the
numerator is unitless or in cycles, the denominator is missing the time
unit.

**Comment by kerrm** [comment]
OK, after some discussion with Paul, I think there's a better solution for the units in d_phase_d_toa, which I've implemented.  Using the conversion should work for the case where a user passes a step with non-second dimension.

**Comment by kerrm** [comment]
Thank god it passes the tests.

**Pull request merged**
