### PR TITLE
Add more informative error message when planet info not found

### PR DESCRIPTION
**Pull request by paulray**
Addresses issue #1390

### CODE REVIEW

**Comment by paulray** [comment]
Someone can give this a quick glance and merge it now.

**Comment by aarchiba** [comment]
Is there a reason not to replace the exception? Either emit a new KeyError with the message you wrote, or some more appropriate exception? `log.error` seems unnecessary when you're raising an exception where you could put the same information.

**Comment by aarchiba** [comment]
Easiest is to just replace `log.error(msg)` with `raise KeyError(msg)`.

**Comment by paulray** [comment]
OK, that looks a little odd because you get nested exceptions, but I guess that is fine:
```
m.phase(ts)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/src/PINT/src/pint/models/solar_system_shapiro.py in solar_system_shapiro_delay(self, toas, acc_delay)
    113                         delay[grp] += self.ss_obj_shapiro_delay(
--> 114                             tbl[grp]["obs_" + pl + "_pos"],
    115                             psr_dir,

~/env/pint/lib/python3.9/site-packages/astropy/table/table.py in __getitem__(self, item)
   1871         if isinstance(item, str):
-> 1872             return self.columns[item]
   1873         elif isinstance(item, (int, np.integer)):

~/env/pint/lib/python3.9/site-packages/astropy/table/table.py in __getitem__(self, item)
    245         if isinstance(item, str):
--> 246             return OrderedDict.__getitem__(self, item)
    247         elif isinstance(item, (int, np.integer)):

KeyError: 'obs_jupiter_pos'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-5-6e04311d7a7f> in <cell line: 1>()
----> 1 m.phase(ts)

~/src/PINT/src/pint/models/timing_model.py in phase(self, toas, abs_phase)
   1221         """
   1222         # First compute the delays to "pulsar time"
-> 1223         delay = self.delay(toas)
   1224         phase = Phase(np.zeros(toas.ntoas), np.zeros(toas.ntoas))
   1225         # Then compute the relevant pulse phases

~/src/PINT/src/pint/models/timing_model.py in delay(self, toas, cutoff_component, include_last)
   1211         for dc in self.DelayComponent_list[:idx]:
   1212             for df in dc.delay_funcs_component:
-> 1213                 delay += df(toas, delay)
   1214         return delay
   1215 

~/src/PINT/src/pint/models/solar_system_shapiro.py in solar_system_shapiro_delay(self, toas, acc_delay)
    117                         )
    118             except KeyError:
--> 119                 raise KeyError(
    120                     "Planet positions not found when trying to compute Solar System Shapiro delay. "
    121                     "Make sure that you include `planets=True` in your `get_TOAs()` call, or use `get_model_and_toas()`."

KeyError: 'Planet positions not found when trying to compute Solar System Shapiro delay. Make sure that you include `planets=True` in your `get_TOAs()` call, or use `get_model_and_toas()`.'

```

**Pull request merged**
