### PR TITLE
Adding H.E.S.S. telescope to the observatory.json file

### PR DESCRIPTION
**Pull request by MRegeard**
Hello, 

I am starting as a PhD student at APC, Paris under the supervision of Arache Djannati-Ataï (@djannati), studying pulsars with HESS telescope. Therefore, I am using PINT to compute phases of pulsars. 

This pull request is to add HESS to the list of observatories in the observatories.json file.
As you can see I already added HESS to the file. I have tested the file on HESS data and it seems to work properly. 

Tell me if you have any comments or anything. I am kind of new on GitHub stuff so I may have not done things the right way.

Cheers.
Signed-off-by: Maxime Regeard <regeard@apc.in2p3.fr>

### CODE REVIEW

**Comment by paulray** [comment]
Thanks for the PR! I'm surprised that HESS wasn't already included, but happy to hear that PINT is being used on HESS data. I guess the times HESS records are already in UTC(GPS) time, so no special clock correction file is needed?

**Comment by abhisrkckl** [comment]
Can you add a CHANGELOG entry?

**Comment by djannati** [comment]
Hi Paul,
We have been developing a pipeline for HESS based PINT since quite a while (3 yrs or so). Till now we have mainly used it to x-check the Tempo2 results, but the aim is to use PINT for next publications. HESS has indeed no clock correction files. The HESS timestamps are based on a GPS receiver on site, so there are no clock correction files. They are recorded as Unix timestamps (a decision made by computing people I guess at the beginning of HESS) with leap seconds corrected for --in principle!.  In the newer gammapy/PINT based pipeline, timestamps are converted and stored as TT. This conversion is still to be double-checked.

**Comment by paulray** [comment]
By any chance do you have the coordinates to add HAWC and MAGIC as well?  That would close #1171 as well

**Comment by dlakaplan** [comment]
> By any chance do you have the coordinates to add HAWC and MAGIC as well? That would close #1171 as well

That would also require knowledge of their clock systems, right?  Or are those available?

**Comment by paulray** [comment]
As far as I'm concerned, this can be merged.

**Pull request merged**
