### PR TITLE
Noise model and GLS fitter

### PR DESCRIPTION
**Pull request by jellis18**
I have added functionality for the standard noise model (EFAC, EQUAD, ECORR, and red noise) and a corresponding GLS fitter. I have tested that this fitter recovers the WlsFitter functionality when no noise parameters are in the par file. I have also tested it against tempo2. The chi-squared values are 3813.79 (PINT GLS) and 3813.71 (libstempo GLS). I've also compared the postfit values and uncertainties against libstempo. In the plots below blue are the parameter differences  and uncertainty differences. By difference I mean abs(x_PINT-x_T2) / x_T2 where x is the parameter value or uncertainty. For all parameters this is less than 1%.

par_diff

dmx_diff

There are still a few things left to do with this. Some things could be cleaned up and some tests added. Also, at the moment we are not storing the red noise ML waveform, which we could do. Also I don't know how to get the "temponest" style parameters to be recognized in the par file. These are parameter like `TNRedAmp`, `TNRedGam`, etc. It looks like maybe PINT expects all par file parameters to be capitalized. I have the functionality in the red noise model to use these but the par file reader doesn't recognize them at the moment.

I can also add the full covariance matrix option as well...

### CODE REVIEW

**Comment by paulray** [comment]
This addresses issue #273 

This is a great step for PINT!  I think that when this is merged, we should tag version 0.6.0, so that we can easily say that noise models were added as of version 0.6

**Comment by jellis18** [comment]
OK, `GLSFitter.fit_toas` now has the `full_cov` option that will let one optionally use the full noise covariance matrix for the GLS fitting. As discussed elsewhere, I would recommend against using this in most cases because it could take a **very** long time for large data sets.

I've tested that it gives the same parameter estimates and uncertainties as the basis-prior method that I showed above. The plots below are the same as those above but now comparing the full covariance matrix method (blue) and the basis-prior method (orange).

par_diff_cov

dmx_diff_cov
 
The differences in parameter and uncertainty estimates between these two methods is negligible.

Now we need to figure out how to deal with `TNRedAmp`-like parameters. Anyone have any suggestions for this?

**Comment by luojing1211** [comment]
I will look into the case sensitive problem, hopefully it will get solved
this afternoon.

-Jing

**Comment by luojing1211** [comment]
@jellis18, when PINT reads the parfile it will alway convert the read in parameter name to upper case. So I would recommend when you define your parameters in PINT, use the upper case. But if you want case sensitized output parfile, we will have to modify the code.

**Comment by luojing1211** [comment]
@Justin this is a quick fix for the case sensitivity problem. 
https://github.com/luojing1211/PINT/blob/a90379775c44b656ea687896d643ca389cf17da0/pint/models/parameter.py#L371
Since this is not a big commitment, you can add it to your PR directly.

**Comment by jellis18** [comment]
OK, if any of the main developers want to take a look at this I think it is basically ready to go.

**Comment by jellis18** [comment]
Merging!

**Comment by jellis18** [comment]
Actually before I merge I will change some of the naming conventions to avoid confusion with the prior class.

**Comment by jellis18** [comment]
Ok, I have changed the name from "prior" to "weight" when referencing the noise model. Merging now.

**Pull request merged**
