### PR TITLE
More typehints

### PR DESCRIPTION
**Pull request by dlakaplan**

### CODE REVIEW

**Comment by abhisrkckl** [comment]
This looks good. Shall I merge this?

**Comment by abhisrkckl** [comment]
PLease add a CHANGELOG entry. There is already a line in `CHANGELOG-unreleased.rst` about type hints, maybe you can update that.

**Comment by abhisrkckl** [comment]
#1709

**Comment by dlakaplan** [comment]
Sorry - I had made a CHANGELOG entry but just forgot to push it.  Done now.

**Pull request merged**
