### PR TITLE
PINTk improvements

### PR DESCRIPTION
**Pull request by dlakaplan**
* Add more explicit zoom status
* Make it so you can use `--version` without par/Tim files
* Print chi^2 and rms info about highlighted points (or all, if none are selected)

### CODE REVIEW

**Comment by dlakaplan** [comment]
Example output from 'x' key:
```
Selected TOAs:                 87
Selected Chi2:          2.0943136e+08
Selected Chi2/Ntoa:     2407257
Selected Weighted RMS:  1158217.9 us
------------------------------------
```

**Comment by dlakaplan** [comment]
Some people were having trouble with the foreground text being hard to read.  This explicitly sets it.  But I don't know if that is good practice (not sure if there is any system-level override).

**Comment by dlakaplan** [comment]
The last change is to fix this:
Screen Shot 2022-05-20 at 3 12 36 PM

**Comment by scottransom** [comment]
This looks good to me.  Want me to merge?

**Comment by dlakaplan** [comment]
I guess I still have a question whether the hardcoding of the foreground color is a good idea.  Maybe if I can figure out what was happening with Lulu's display, that would help.  I couldn't reproduce it.

Also, is the formatting for the chi^2 output as desired?  Should it maybe have a preceding divider?

**Comment by dlakaplan** [comment]
OK, I checked with Lulu.  She has the apple "dark mode" on, which changes around some of the colors.  I can't fully reproduce everything that she sees (for instance, even with dark mode on I still see black text) but I think I can try to understand where those settings come from.

**Comment by scottransom** [comment]
I think I'm fine with the chi^2 output.  Although a preceding divider might be good, since I think the other output has that.

**Comment by scottransom** [comment]
OK, can I merge this now?

**Comment by dlakaplan** [comment]
I think so, although if you wanted to double-check that the colors look OK on another system that could be helpful.

**Comment by scottransom** [comment]
OK.  I'l check on a couple systems, and if they look good, will merge.

**Comment by scottransom** [comment]
Tried it on three very different systems and they all looked good.  I'm merging.

**Pull request merged**
