### PR TITLE
Solar wind model fix

### PR DESCRIPTION
**Pull request by aarchiba**
This should match the version from Edwards+ 2006.

### CODE REVIEW

**Comment by aarchiba** [comment]
Tests required.

**Comment by paulray** [comment]
I say we merge this and #892 now and leave the work of adding better testing to issue #893

**Comment by aarchiba** [comment]
I might need to rebase this after #892 is merged (it's based on #892 in my git).

**Comment by aarchiba** [comment]
Er, but otherwise I think I'm with you on merging them both now and adding tests later.

**Comment by paulray** [comment]
OK, the first one is merged

**Comment by aarchiba** [comment]
Rebased, ready to go if the code looks okay

**Comment by aarchiba** [comment]
Closes #733

**Comment by paulray** [comment]
I'm going to merge now and I'll run some comparisons with Tempo2 after my 2pm telecon

**Comment by aarchiba** [comment]
> I'm going to merge now and I'll run some comparisons with Tempo2 after my 2pm telecon

If you wanted to make a couple of .tim/.par combinations with tiny sets of TOAs and a -solarangle flag (using the general2 plugin) I could write a test that checked that.

**Pull request merged**
