### PR TITLE
Fix GLS and wideband chi-squared

### PR DESCRIPTION
**Pull request by aarchiba**
Computation of the GLS and wideband chi-squared were wrong before in red-noise cases. Also the GLS computation incorrectly froze all parameters.

### CODE REVIEW

**Comment by luojing1211** [comment]
This looks good. Is it a good idea to separate these fitting functions from the fitter, so one doesn't need to build a fitter in the residual? Of course, it would be a separate PR.

**Comment by pennucci** [comment]
It does look good.  I'm still curious about the choice to not cache the chi2 value at the end of fit_toas, but I guess I can understand why.

**Comment by luojing1211** [comment]
It matches how TOAResidual's Chi2. If one only uses it in the fitter, caching chi2 is not a problem since the fitter rebuilds the residual class after every fit. However, if one modifies the model in the residual class, `Residusal.model`, the cached chi2 will be wrong.

**Comment by aarchiba** [comment]
> It does look good. I'm still curious about the choice to not cache the chi2 value at the end of fit_toas, but I guess I can understand why.

That chi2 value is computed based on pre-fit values of the orbit. It will be valid, for example, even if the output SINI > 1. It will not be the same value one would obtain if one ran calc_chi2 on the residuals object.

**Comment by aarchiba** [comment]
> This looks good. Is it a good idea to separate these fitting functions from the fitter, so one doesn't need to build a fitter in the residual? Of course, it would be a separate PR.

I don't think the Fitter introduces any appreciable extra machinery. And it is conceptually clearer here: you really do need to fit for the noise instance to get a useful chi-squared, and the way you fit for things in PINT is using a Fitter.

**Comment by aarchiba** [comment]
> > It does look good. I'm still curious about the choice to not cache the chi2 value at the end of fit_toas, but I guess I can understand why.
> 
> That chi2 value is computed based on pre-fit values of the orbit. It will be valid, for example, even if the output SINI > 1. It will not be the same value one would obtain if one ran calc_chi2 on the residuals object. This is demonstrated in one of the test cases.

There's an argument to be made that `fit_toas` should not return its `chi2` value at all, because unless all parameters are frozen it is not the chi-squared value corresponding to any specific set of model parameters.

**Comment by paulray** [comment]
> There's an argument to be made that fit_toas should not return its chi2 value at all, because unless all parameters are frozen it is not the chi-squared value corresponding to any specific set of model parameters.

I haven't been following this discussion, but I don't quite understand what this means. Can you explain?  In any chi2 minimization fitter, don't you end up with a set of final parameters and a chi2 value that corresponds to the data-model for that set of parameters?

There is a mention above about computing chi2 from pre-fit values. Why would that be done? Don't you normally want chi2 after a fit (unless you are trying to find delta-chi2 from the fitting process)?

**Comment by scottransom** [comment]
I agree with @paulray.  I'm not understanding that.  Heck, we are using chi^2 as the function to be minimized by the fitter.  So it is definitely meaningful in some way.  The main thing is that we would like it to mean what most people *think* chi^2 usually means.

@aarchiba Are you specifically talking about returning a chi^2 pre-fit when an actual fit is not done?  I totally think it is valid to ask what the chi^2 is of any model with any set of parameters (frozen or not, it doesn't matter if you aren't fitting).  But *post-fit*, we should really be able to know the true iterated/converged post-fit chi^2 and # of DOF.  And that should (IMO) totally be returned by the fitter after fitting.

**Comment by aarchiba** [comment]
> > There's an argument to be made that fit_toas should not return its chi2 value at all, because unless all parameters are frozen it is not the chi-squared value corresponding to any specific set of model parameters.
> 
> I haven't been following this discussion, but I don't quite understand what this means. Can you explain? In any chi2 minimization fitter, don't you end up with a set of final parameters and a chi2 value that corresponds to the data-model for that set of parameters?
> 
> There is a mention above about computing chi2 from pre-fit values. Why would that be done? Don't you normally want chi2 after a fit (unless you are trying to find delta-chi2 from the fitting process)?

No. Well, in any reasonable fitting algorithm you would, but we do not use a fitting algorithm. PINT (and I think tempo/tempo2) does a "fit" by computing residuals and derivatives at the pre-fit model parameters, then treating that as a linear least-squares fitting problem to compute the needed change in the model parameters. It then adjusts the model in this way and returns the new parameters. It does not ever evaluate the model at these new parameter values (which are often invalid); the chi-squared value it returns is an estimate of what the chi-squared should be if the linear least-squares problem were exact. 

The new residuals object evaluates the model at the new parameter values (often obtaining nothing but NaN), and if `.calc_chi2` is run, computes the chi-squared value at those model parameters.

**Comment by aarchiba** [comment]
> I agree with @paulray. I'm not understanding that. Heck, we are using chi^2 as the function to be minimized by the fitter. So it is definitely meaningful in some way. The main thing is that we would like it to mean what most people _think_ chi^2 usually means.
> 
> @aarchiba Are you specifically talking about returning a chi^2 pre-fit when an actual fit is not done? I totally think it is valid to ask what the chi^2 is of any model with any set of parameters (frozen or not, it doesn't matter if you aren't fitting). But _post-fit_, we should really be able to know the true iterated/converged post-fit chi^2 and # of DOF. And that should (IMO) totally be returned by the fitter after fitting.

The issue right now is that we need a chi-squared value with the correct statistics in order to support the F test. For models with uncorrelated errors, this just means we need a weighted-mean-subtracted set of residuals, or to subtract the weighted mean in the chi-squared computation. For models with correlated errors, to get reasonable statistics we need to operate on the whitened residuals, which requires a fitting procedure (since our residuals object is not whitened - as I understand it whitening is subtracting a best-fit noise instance, analogous to subtracting the weighted mean).

**Comment by pennucci** [comment]
I think I understand that but assuming convergence (maybe not a good assumption, but let's call that "post-fit"), then the values returned by either fit_toas or calc_chi2 should give you the right statistics I think.  As per my original comment regarding "pre-fit" calculations -- all I'm getting at is the simple intuition that the chi2 value is related to the evaluation of the likelihood, so given the data, some model parameters, including a noise model, you should be able to get a value for the likelihood without a fit.  I understand that the GLS tricks we use make this hand-wavy, but that's what I was getting at.  And w.r.t. the weighted mean, see #810; a number of us have noticed in v0 timing that post-fit (whitened) residuals have a non-zero mean.

**Pull request merged**
