### PR TITLE
Different way of doing tests and new travis ci with python3 tests

### PR DESCRIPTION
**Pull request by jellis18**
Here are some changes that should make the ci tests work more smoothly. It appears that when running the shell script for tests, it would only fail if the tests failed in the setup stage and not in the test part of the unit tests as unit test is not meant to fail there but simply report that the test failed. They are as follows

1. Use `nosetests` directly by adding a few lines to `setup.cfg`. Now to run tests one can do `python setup.py nosetests`. 
2. Change `.travis.yml` to work with python version 2.7 - 3.6 but allow failures for all python 3 versions until problems related to PR #220 are worked out.
3. Change `.travis.yml` to use requirements files and pip instead of `Anaconda`. This is actually useful for developers too.
4. Don't test `test_astropy_times.py` to get around problems mentioned in #224.
5. Use `unittest` wherever possible. 

With this changes `travis` will fail when it is supposed to and we can switch off the `allow_failures` line once we get python 3 working. I think we should try to merge this ASAP to help out with other PRs so that we know if our tests are actually passing or not.

### CODE REVIEW

**Comment by matteobachetti** [comment]
Hi, one small and easy fix that allows to at least import toa in Py 3: use 
`from builtins import super`
and substitute all occurrences of `super(class).__new__(something)` with `super().__new__()`

**Comment by jellis18** [comment]
Another thing that we may want to do along the lines of tests is to make PINT/master a [protected branch](https://help.github.com/articles/defining-the-mergeability-of-pull-requests/) and have a requirement that the CI tests pass before being able to merge. 

@nanograv/pint, @nanograv/core, any comments on this PR?

**Comment by jellis18** [comment]
Should we merge this?

**Comment by paulray** [comment]
It looks pretty good to me.  Two questions:
(1) Why do we need to support so many versions of Python 3? It it important to have so many?
(2) Shouldn't Sphinx be in the requirements somewhere (e.g. requirements-dev.txt), since we use it to build the docs?

**Comment by jellis18** [comment]
> (1) Why do we need to support so many versions of Python 3? It it important to have so many?

I guess a better question is why not? I'm really not very accustomed to Python 3 but most projects I have seen have tests for all versions. Although as you see, at the moment most tests will fail with Python 3 as there are a bunch of fixes that need to be made in a separate PR.

> Shouldn't Sphinx be in the requirements somewhere (e.g. requirements-dev.txt), since we use it to build the docs?

Yes that is definitely true. I forgot about docs since I was just making sure we had what we needed to run the tests. I'll go back and add any extra dependencies (including) Sphinx that we may need for the docs.

**Comment by paulray** [comment]
@jellis18 Cool, I'm fine with all the Python 3 versions, I guess.  Someday when we get Python 3 support working, we may find that we have to drop some of those versions if they have some issue we can't deal with.

On Sphinx, the tests used to require sphinx because they ran doctests, but we no longer build the docs as part of the test script because there are many that aren't written in a way that will pass.

**Comment by jellis18** [comment]
OK, I've pushed changes adding Sphinx and astropy helpers (which the docs seem to need). 

One thing related to this PR is that we will also want to change some statements in the wiki relating to testing and installation.

For example in [Installation Notes](https://github.com/nanograv/PINT/wiki/Installation-Notes) we can add that `pip install -r requirements.txt` will install required packages and that `pip install -r requirements_dev.txt` will install development tools. Also, I find that a better way to do development builds is to use `python setup.py develop` which makes symbolic links so that changes are seen without the need to re-install. This has the added benefit that you don't need to set paths and it all works just like a normal install. In the test section we can use `python setup.py nosetests`. These can then be put in the [Git Workflow](https://github.com/nanograv/PINT/wiki/Git-Workflow) section as well.

**Comment by luojing1211** [comment]
@all, do you think this is ok to merge now? We can do the modification on wiki quite easy.

**Comment by paulray** [comment]
I fine with merging this now

**Comment by luojing1211** [comment]
I second. Merging.

**Pull request merged**
