### PR TITLE
WIP: Standardize citations in code

### PR DESCRIPTION
**Pull request by abhisrkckl**
The citation conventions are all over the place right now. This PR tries to standardize them like

```
Lorimer and Kramer [lk2004_]

.. _lk2004: https://ui.adsabs.harvard.edu/abs/2004hpa..book.....L/abstract
```

This follows #1460 and #1490.

### CODE REVIEW

**Comment by dlakaplan** [comment]
I think you need to check the RTD: not all of the links are rendering correctly.

**Comment by dlakaplan** [comment]
Personally I like to be a little more explicit about the references:
```
- Taylor and Weisberg (1989), ApJ, 345, 434 [tw89]_

    .. [tw89] https://ui.adsabs.harvard.edu/abs/1989ApJ...345..434T/abstract
```
so that it gives both the actual info and a link to ADS (in case somebody has a local copy etc, they shouldn't be forced to go to ADS to see what the paper is).

**Comment by dlakaplan** [comment]
We could also consider https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html

**Comment by abhisrkckl** [comment]
This PR is stale. So I am closing it.

**Pull request closed without merging**
