### PR TITLE
bugfix and added GLF2 in glitch.py

### PR DESCRIPTION
**Pull request by dcfidalgo**
Hi,
- glitch.py: Fixed a small bug (mix-up with astropy units) and added the parameter GLF2_ since tempo2 has it and i guess it does not hurt to have it as well. I also extended a bit the check on the parameters.
- fermi_toas.py: Added two more arguments to the load_Fermi_TOAs method (minmjd and maxmjd, so it does not create TOA instances for events you are not interested anyways). 

David

### CODE REVIEW

**Comment by paulray** [comment]
Why is this not merged yet?

@dcfidalgo Can you rebase this on the current master to clear up the conflicts?  It would be great to add a small test to test the GLF2 functionality as well.

**Comment by paulray** [comment]
The Fermi part of this has now been added and merged.

@luojing1211 do you want to add GLF2 to the glitch model?  Enough has changed since this PR was filed that we should probably just close this and make that change independently.

**Comment by luojing1211** [comment]
Will do.

**Comment by luojing1211** [comment]
Hi @paulray, Does GLF2 the highest order we are currently modeling the Glitch?

**Comment by paulray** [comment]
I've never actually used GLF2 myself, but I think we can safely assume that GLF2 is the highest order we need to be able to model.

**Comment by luojing1211** [comment]
This problem should be fixed by PR #293. @paulray do you want to take a look at PR #293

**Comment by paulray** [comment]
This has been superseded.  Closing.

**Pull request closed without merging**
