### PR TITLE
Fix sphinx build by specifying theme explicitly

### PR DESCRIPTION
**Pull request by dlakaplan**
Also pinning some versions, but that doesn't seem to help or hurt.

### CODE REVIEW

**Comment by abhisrkckl** [comment]
Is the "if not on_rtd" part required?

**Comment by dlakaplan** [comment]
I left it.  I can comment it out if that is clearer.

**Comment by abhisrkckl** [comment]
Wouldn't it be better not to pin versions if it makes no difference? Readthedocs or sphinx may drop support for old versions in the future.

**Comment by abhisrkckl** [comment]
I think that if statement just looks confusing

**Comment by dlakaplan** [comment]
My worry is that a major version bump (e.g., sphinx 6->7) may break things anyway.  Some people prefer pinning exact versions to general requirements.

**Pull request merged**
