### PR TITLE
Bayesian information criterion

### PR DESCRIPTION
**Pull request by abhisrkckl**
A function for computing BIC similar to AIC

### CODE REVIEW

**Comment by dlakaplan** [comment]
Can you not add in the WB version?  Is it that hard to do (I assume we would just add the chi^2 for TOAs to the chi^2 for DM)?

Also, while not necessary to do it for all of the functions, could you add type annotations for this and the AIC function?

**Comment by dlakaplan** [comment]
It also might be nice with AIC and BIC to have a note illustrating how they could be used (i.e., compute for two models, how to compare) and add references?

**Comment by abhisrkckl** [comment]
More detailed documentation added.

**Comment by abhisrkckl** [comment]
> Can you not add in the WB version? 

I'll do that as a separate PR.

The problem is that the `WidebandTOAResiduals.calc_chi2` function calls `WidebandTOAFitter`, and I don't fully understand what it does under the hood. Depending on what exactly it does, my understanding of how to implement the normalization term in the log-likelihood may be wrong. I want to get a better hang of what's going on there before attempting to add AIC & BIC for WB data.

**Comment by dlakaplan** [comment]
Docs are good.  I still think it would be nice to incrementally add type hinting, but if you don't want to do that I can merge this.

**Comment by abhisrkckl** [comment]
I tried adding type hints. But importing TimingModel and TOAs into pint.util leads to circular imports.

**Comment by dlakaplan** [comment]
OK, I see.  I _think_ you can give type hints as strings, and they will only be evaluated later.  But I am not 100% sure (https://mypy.readthedocs.io/en/stable/runtime_troubles.html#runtime-troubles). I feel like I did this recently but I can't remember where.

**Comment by dlakaplan** [comment]
So yes, look at:
https://github.com/nanograv/PINT/blob/master/src/pint/models/astrometry.py#L641
I think there I put in a type hint for a return value as a string since the class was only defined later in that file.

**Comment by abhisrkckl** [comment]
Thanks... I have added type hints.

**Comment by dlakaplan** [comment]
Looks great.  I can merge it if you are set.

**Comment by abhisrkckl** [comment]
Yes. Please do.

**Pull request merged**
