### PR TITLE
Convert to pyproject install

### PR DESCRIPTION
**Pull request by dlakaplan**
Generated `pyproject.toml` using https://pypi.org/project/ini2toml/.  Removed `setup.cfg`.  Kept `setup.py` as it's needed for versioning.

For me this worked OK with `pip install -e .` Not getting the warning messages (#1846).  Still should test other build methods. It would help if others can try this too.

### CODE REVIEW

**Comment by dlakaplan** [comment]
Looks like install during the GitHub CI tests worked...

**Comment by dlakaplan** [comment]
Just did a fresh install:
```
conda create -n pintinstalltest python=3.12
conda activate pintinstalltest   
pip install .  
```
and it seemed to work too

**Comment by dlakaplan** [comment]
@paulray : are you able to see if this can still be packaged for pypi and conda (is there any way to do that without releasing a new version)?

**Comment by paulray** [comment]
In our Makefile, when I do a `make release`, it runs the following:
```
dist: clean ## builds source and wheel package
        python setup.py sdist
        python setup.py bdist_wheel
        ls -l dist
```
@dlakaplan is that still the right thing to run?

**Comment by paulray** [comment]
I get a few deprecation and other warnings when I build the source and wheel packages. See attached log. Are these ignorable, or should we fix them?
[distlog.txt](https://github.com/user-attachments/files/17440016/distlog.txt)

**Pull request merged**
