### PR TITLE
WIP: Performance improvements

### PR DESCRIPTION
**Pull request by abhisrkckl**
1. Change `Quantity.decompose()` to `Quantity.to()` --- see #1641 
2. Optionally cache parameter masks.
3. Minimize Quantity operations in `ScaleToaError.scale_toa_sigma`

Item 1 gives a slight performance advantage (~5%) overall.

Item 2 gives almost 10x improvement in timing models where maskParameters (e.g. JUMPs) are present. The caching is of course turned off by default, and can be enabled by calling `model.lock(toas)`. Mutating the `toas` object after calling `model.lock(toas)` leads to undefined behavior (in practice, some unhelpful exception down the line in the best case scenario, and wrong result in the worst case scenario).

Item 3 gives around 40% improvement in models where ScaleToaError is present.

These performance improvements are important for Bayesian timing & noise analysis (#1407) and frequentist noise estimation (#1639).

### CODE REVIEW

**Comment by abhisrkckl** [comment]
Performance comparison:
```
from pint.models import get_model_and_toas
from pint.residuals import Residuals
from pint.logging import setup as setup_log
from time import time

setup_log(level="WARNING")

m, t = get_model_and_toas("J1909-3744.par", "J1909-3744.basic_sim.tim")

res = Residuals(t, m)

repeat = 100
start = time()
for _ in range(repeat):
    res.calc_chi2()
end = time()

print(f"time elapsed without caching = {(end-start)/repeat:.2e} s")


m.lock(t)
res = Residuals(t, m)

repeat = 100
start = time()
for _ in range(repeat):
    res.calc_chi2()
end = time()

print(f"time elapsed with caching = {(end-start)/repeat:.2e} s")
```

> time elapsed without caching = 5.44e-03 s
> time elapsed with caching = 4.69e-04 s

**Comment by dlakaplan** [comment]
Would using `@cache` or `@cached_property` be better than writing your own caching?

**Comment by abhisrkckl** [comment]
> Would using @cache or @cached_property be better than writing your own caching?

That's probably a better idea. I'll try this.

**Comment by abhisrkckl** [comment]
> If you are putting in changes to how units are handled, it would also make sense to add those guidelines to the coding style documents.

I am still experimenting with this and figuring out what's performance-critical and what's not. I am planning to make my changes as small as possible.

**Comment by abhisrkckl** [comment]
> There are some other areas where modifying TOAs can require recalculating various things, such as in https://github.com/nanograv/PINT/issues/1512 . Rather than have an explicit lock() method, would it work to have a TOA timestamp/checksum associated with the TOAs object and then copy that into the model? Then this could be copied into the model and checked.

Wouldn't a checksum be expensive to compute, since it has to process the entire TOA object?

**Comment by abhisrkckl** [comment]
I have decided that it will be better to divide this into multiple PRs focusing on different aspects of performance. So I am closing this.

**Pull request closed without merging**
