### PR TITLE
Add ability to change binary epoch

### PR DESCRIPTION
**Pull request by rossjjennings**
This is the last major piece of #491. For now I've implemented it at the "PINT wrapper class" level; i.e., you can't do it with a stand-alone binary model, for reasons related to #639. I ran into some annoyances around missing parameters that I detailed in #642. I could deal with them, but not without producing some fairly messy code -- take a look at the bit that gets `PB` and `PBDOT`. 

I'm also ignoring orbital frequency/period derivatives higher than the first in computing the new epoch. While this omission can lead to small inaccuracies, it doesn't affect models that don't have these higher derivatives (which is most of them), and even for the ones that do, the results should be fine as long as the model is refit afterwards.

I should also point out that I had to override the `change_binary_epoch()` function for ELL1 models, and a lot of code is duplicated between the two implementations. I don't know a good way to reduce this duplication, so I've left it as is.

### CODE REVIEW

**Comment by rossjjennings** [comment]
I considered using the `model.binary_instance.orbits()` function, which takes into account all orbital frequency derivatives, to compute the orbital phase as part of finding the new epoch, but I also needed the inverse of this function, which is currently not implemented and would be quite a bit trickier to implement.

**Comment by rossjjennings** [comment]
The initial test failures were due to PINT not recognizing the H3 line in one of my test par files. Maybe that needs to be its own issue. For now I've just commented out the line.

**Comment by paulray** [comment]
There is an important question here.  Should these change epoch functions be such that the residuals before and after the change are identical (to machine precision)?  Many people may use them as such.  But, often it is useful to do the epoch change approximately then re-fit to get the precise values.  So, where possible, the unit tests should verify that the residuals don't change to some strict tolerance. Where that is NOT possible, the code should certainly emit Precision Loss warning of some kind, and maybe that should be an error unless the user specifies some approximate_ok=True flag or something like that.  

Note that form some of the rapidly evolving orbits, using the first order approximation may not come out very close at all.

**Comment by rossjjennings** [comment]
@paulray I discussed this a little with @scottransom at the meeting, and came away with the impression that having some version of this functionality soon is more important than having it be perfect. But I agree that the more guarantees we can make around accuracy and precision, the better.

Do you have examples of rapidly evolving orbits that I could write tests against?

**Comment by paulray** [comment]
Yes, I agree that something is better than nothing, but **definitely** have it emit a warning.

Here is a par file with a lot of orbital evolution:
```
PSR                            J2339-0533
EPHEM                               DE421
RAJ                     23:39:38.74105423
DECJ                    -5:33:05.10815967
PMRA                                4.147
PMDEC                             -10.311
PX                                    0.0 0 0.0
POSEPOCH           55792.0000000000000000
F0                   346.7133792204550673 1 2e-11
F1              -1.6942169221776437339e-15 1 3e-19
PEPOCH             55792.0000000000000000
START 54682
FINISH 58826
BINARY ELL1
A1                     0.6116660540086037 1 3.97439427207e-06
FB0             5.9938735816315316055e-05 1 1.1635526271371187127e-13
TASC               55791.9182103258863208 1 5.4132986898782e-07
EPS1                                  0.0 0 0.0
EPS2                                  0.0 0 0.0
FB3             -1.7795323933159306739e-33 1 1.8815636923779602566e-35
FB2             1.4553150100638518123e-26 1 3.3303916978609588776e-28
FB1               7.03725434744961224e-19 1 5.4332669868139948757e-21
FB7             -1.1468823953863174394e-62 1 1.5582489154671737184e-64
FB6             -4.2593887032115926134e-56 1 1.4278485036990097178e-57
FB5             5.3220305161746596376e-48 1 6.9531355833051827763e-50
FB4             -2.912644103931864879e-41 1 8.3840111451374732775e-43
FB9             -8.8475561365212462225e-78 1 1.0662311609509164363e-79
FB8              5.250316158222745923e-70 1 7.0874959224021488374e-72
FB10            2.2044791630302574554e-85 1 5e-86
FB11            -1.335419320262546109e-92 1 1e-93
FB12            2.807404079260208171e-100 1 1e-101
TZRMJD             56552.1042084326638773
TZRSITE                               bat
TZRFRQ                                0
UNITS TDB
```

**Comment by scottransom** [comment]
@paulray That parfile is one which I do not think we should handle internally at all.  That's because polynomials are so specific to their ranges of validity.  And changing TASC for that model dramatically changes all of that stuff.  (Note:  what I would do for that is to record all my absolute rotation numbers for that model, change TASC and refit demanding that the rotation numbers between TOAs are the same.  And even that, given what order the polynomial is, it could fail).

I suggest that we be able to handle PBDOT and OMDOT (and maybe XDOT).  And anything beyond that we punt on, do the "DOT"s and say that to get a good fit the user needs to use absolute phases and a re-fit.  And we should *always* recommend that the user refits after the EPOCH changes.

**Comment by paulray** [comment]
Yep, I know that parfile is a nightmare!  So, I think it is fine to handle a subset of cases, as long as make sure that users won't think PINT is doing the right thing on par files that it can't do the right thing on.

**Pull request merged**
