### PR TITLE
Maximum-likelihood fit for ECORR

### PR DESCRIPTION
**Pull request by abhisrkckl**
- Enables maximum-likelihood fitting for ECORR parameters when time-correlated noise components are absent.
- Only available in `DowhillGLSFitter`.
- Also works in pintk
- Fitting for time-correlated noise components is too slow at the moment. (May come back to this later).
- Added an example notebook for noise fitting.

### CODE REVIEW

**Comment by abhisrkckl** [comment]
Preliminary result:
image
The corner plot shows the ENTERPRISE result. The blue lines show the PINT maxlike estimate.

**Comment by abhisrkckl** [comment]
A more detailed simulated example with multiple ECORRs:
image

**Comment by abhisrkckl** [comment]
I have given up on implementing the ecorr derivatives for the time being. The fitting works fine without them, albeit slower (but not prohibitively so). I'll come back to this after finishing the paper.

**Comment by abhisrkckl** [comment]
One more simulated example:
image

The corner plot is from ENTERPRISE analysis.
Blue "truth" lines represent the injected values.
Red error bar plots represent the PINT maximum-likelihood estimates.

**Comment by abhisrkckl** [comment]
https://nanograv-pint--1673.org.readthedocs.build/en/1673/examples/noise-fitting-example.html

**Comment by dlakaplan** [comment]
While I didn't look line-by-line, I can merge this if you want.  It shouldn't hurt anything existing and more use might exposure any issues (or it might just be a great new feature).

**Comment by abhisrkckl** [comment]
Yes. Please merge this.

**Comment by dlakaplan** [comment]
I think there is an issue with the ephemeris hosted at NANOGrav (@JPGlaser ).  Probably we can ignore this?

**Comment by abhisrkckl** [comment]
Yes. I reran the failed ephemeris_connection tests, but they failed again. I think we can ignore that.

**Pull request merged**
