### PR TITLE
Update README with paper info

### PR DESCRIPTION
**Pull request by abhisrkckl**
This is a purely documentation update.

### CODE REVIEW

**Comment by dlakaplan** [comment]
Looks good, but do you want to wait until you hear back about paper 2?

**Comment by abhisrkckl** [comment]
OK That's fine. I'll remove the part about the second paper. That can be added later

**Comment by abhisrkckl** [comment]
Removed reference to paper 2

**Comment by dlakaplan** [comment]
Wouldn't it be better to do this as a citation.cff file (like #1577) instead?

**Comment by abhisrkckl** [comment]
I think that's less visible than this. 

Also, the cff file needs a lot of information and is a lot of work (I tried before and gave up).

**Comment by dlakaplan** [comment]
I just tried in #1767 and it looks OK.  We can differentiate between the full citation (all contributors) and the preferred journal citation.  Which isn't to say that we can't do both.

Personally I think including the full bibtex doesn't look great.  How about just a link to https://ui.adsabs.harvard.edu/abs/2021ApJ...911...45L/exportcitation?

**Comment by abhisrkckl** [comment]
Closing this because cff file was added

**Pull request closed without merging**
