### PR TITLE
Randomfit checkbox

### PR DESCRIPTION
**Pull request by champagne-cmd**
Added checkbox to pintk GUI to turn random model plotting on and off.

### CODE REVIEW

**Comment by paulray** [comment]
Fixes #692

**Comment by scottransom** [comment]
Nice!  :-)

**Comment by paulray** [comment]
Thanks Chloe! One little tip is that this PR includes the changes from your other PR. This means it can't be merged without merging in those changes as well. Not a big deal here since both are ready to be merged. But, in the future it is a bit better if you make a new feature by starting with a new branch off of master. Then each feature PR can be merged without affecting the other.
See here: https://github.com/nanograv/PINT/wiki/Git-Workflow and here: https://nanograv-pint.readthedocs.io/en/latest/contributing.html for some tips.

**Comment by champagne-cmd** [comment]
Ah, my apologies @paulray, I thought I had branched off the master. I will be more mindful next time!

**Comment by paulray** [comment]
No worries! I just tried it and the checkbox works great!
I notice that the random models only actually get plotted if the X-axis is MJD or Rounded MJD. Would it be hard to make them appear for other X-axes (at least "Year")?

**Comment by paulray** [comment]
Also, since you are editing pintk code, could you look into this deprecation warning? Presumably it is just a tiny fix:
```
/Users/paulr/src/PINT/src/pint/pintk/plk.py:695: MatplotlibDeprecationWarning: Support for passing a (n, 1)-shaped error array to errorbar() is deprecated since Matplotlib 3.1 and will be removed in 3.3; pass a 1D array instead.
```

**Comment by champagne-cmd** [comment]
I fixed the deprecation warning @paulray. I will need to study the code more to figure out the plotting with other variables, but I will see what I can do.

**Comment by paulray** [comment]
Wow, I love the simplification!  That makes me wonder if the rest of the `reshape([-1,1])`'s need to be there? I had never seen that particular usage and had to look up what -1 meant to `reshape()`. If they need to be reshaped 1-d arrays, then why not use `reshape(-1)` instead? Just curious.

**Comment by champagne-cmd** [comment]
I believe reshape(-1) creates a (1, N) array, whereas reshape([-1, 1]) creates an (N, 1) array. The x and y (and error arrays formerly) take in (N, ) arrays or (2, N) arrays. So reshape(-1) wouldn't work for the x and y values.

**Comment by paulray** [comment]
Hmm. When I do reshape(-1), I get a 1-d array of length N, i.e. the shape is (N, ). I don't really know why that code ever was using 2-d arrays with one dimension being length 1 (either (N,1) or (1,N)), but I haven't looked at any of that code so maybe there was some reason. Anyway, the plotting now works great with no warnings.  Fantastic work!

**Comment by scottransom** [comment]
Yeah, why are reshapes required at all?  I don't understand that...  I would have thought that everything was a 1-D array.

**Comment by champagne-cmd** [comment]
For the x values, it seems like the units attached are causing problems. When I remove reshape, it throws an error saying 'only dimensionless scalar quantities can be converted to Python scalars'. So perhaps the reshape serves to remove units as well as ensure the array is the correct dimensions?

**Comment by luojing1211** [comment]
The correct way to remove unit is Quantity.value(). reshape may remove the unit, however, when numpy fully supports the unit, it will fail.

**Comment by paulray** [comment]
Ah! I didn't realize the goal was to remove the units!  Those reshapes have been there from the beginning with Jonathan wrote the code.  The "correct" way is to enable `quantity_support()` from astropy.visualization. Then you don't have to remove units at all. See: https://docs.astropy.org/en/stable/visualization/matplotlib_integration.html#plotting-quantities

**Comment by luojing1211** [comment]
That is the correct way to do it, instead of removing the unit.

**Comment by champagne-cmd** [comment]
Huh, I used quantity_support and the x and y values now don't need reshape. However, now the y error is throwing 'matplotlib.units.ConversionError: Failed to convert value(s) to axis units: []' 
I'm still not sure how to fix this...

**Comment by paulray** [comment]
Hmm. Presumably `yvals` and `yerrs` need to have compatible units.  Could one of them have lost their units?

**Comment by champagne-cmd** [comment]
They both seem to have units of us.

**Comment by paulray** [comment]
Just a guess, but maybe you called `quantity_support()` in this routine, so it wasn't enabled when the axes were created?  I think you want to call it only once, so I'd put it at the top of plk.py just after matplotlib is imported. That should make it a 'global' setting.

**Comment by scottransom** [comment]
Yeah, that might be it. However, what happens if we change the axes (i.e. MJD to year or orbital phase).  Does that need to completely reset the axes?

**Comment by paulray** [comment]
Beats me! :-)

**Comment by champagne-cmd** [comment]
Nope, I called it inside the routine and at the top of the file, it still gives me the same error. I will try to do some more digging.

**Comment by paulray** [comment]
Worst case you can just resort to .value as Jing suggested

**Comment by champagne-cmd** [comment]
Ok, I used .value in plotErrorBars since I couldn't figure out a work-around with quantity_support or time_support. Also, I modified the random model plotting so that it would plot with MJDs and years. While playing around with that, I noticed there was a small bug in the orbitalphase() function in pulsar.py -- the return was incorrect for the case where a non-binary pulsar was used, so I amended that.

**Pull request merged**
