### PR TITLE
Piecewise-constant chromatic variations (CMX)

### PR DESCRIPTION
**Pull request by abhisrkckl**
This depends on #1616. So That PR needs to be merged first. --- DONE.

Partially implements #1661.

### CODE REVIEW

**Comment by kerrm** [comment]
This looks like a lot of work!
Overall it looks fine to me.
I think the big thing is to add to the test an explicit verification that the chromatic calculation is correct.  You've got some TOAs at different freqs, so verify that
(1) the delay is correct given the amplitude and chromatic index
(2) that the delay does *not* affect TOAs outside of any ranges
(3) that the lookup of ranges is correct, so do (1) for multiple events

**Comment by mtlam** [comment]
I took a look and agree with @kerrm, the base functionality looks great. After any potential additional testing components might be added beyond the recent commits, I think it would be great to get this functionality in.

**Comment by abhisrkckl** [comment]
> I think the big thing is to add to the test an explicit verification that the chromatic calculation is correct. You've got some TOAs at different freqs, so verify that
> (1) the delay is correct given the amplitude and chromatic index
> (2) that the delay does not affect TOAs outside of any ranges
> (3) that the lookup of ranges is correct, so do (1) for multiple events

Added tests for this

**Comment by abhisrkckl** [comment]
I think this can be merged.

**Pull request merged**
