### PR TITLE
Add ability to change POSEPOCH

### PR DESCRIPTION
**Pull request by rossjjennings**
This is a major step toward solving #491. I've added a `change_posepoch()` function to the `AstrometryEquatorial` and `AstrometryEcliptic` classes, along with a basic test for it that covers the ecliptic case (in tests/test_change_epoch.py). The new function reuses epoch-updating functionality from `get_psr_coords()`. For that reason, I made another change here that is, in retrospect, logically independent: the astropy coordinate object returned by `get_psr_coords()` now includes the proper motion, and `get_params_as_ICRS()` now relies on it, so everything is in the same place. I added a test in tests/test_astrometry.py to make sure this didn't break coordinate conversions.

### CODE REVIEW

**Comment by scottransom** [comment]
This is great, @rossjjennings !  Thanks so much!  I've been wondering about the PM aspects of astropy coordinates.  While you were looking at the astrometry code, did you get a sense of how hard it would be to completely switch over to using astropy PM stuff rather than our explicit PM functionality?

**Comment by rossjjennings** [comment]
@scottransom The `params_as_ICRS()` method of `AstrometryEcliptic` was already using astropy proper motion internally. The main explicit PM functionality left is the epoch-updating functionality. Astropy 3.0 has its own `apply_space_motion()` for this, but we can't use it as long as we continue to support python 2.7.

**Comment by rossjjennings** [comment]
The test for the `change_posepoch()` function was failing on Python 2.7 because the attribute I used to extract the proper motion in the test wasn't available in Astropy 2. I just added a commit that should fix that, so all the tests should pass except the ones in the tox build that are still failing due to Astropy 4.

**Comment by rossjjennings** [comment]
@scottransom @luojing1211 @paulray What are your thoughts on merging this? I have some thoughts for building on it (related to #610 for instance), so it would be nice to get it merged soon. It's also substantial enough that we might want to discuss it more first, though.

**Comment by scottransom** [comment]
I've done a quick look and I think it looks pretty good.  I'd be happy for it to be merged if @luojing1211  and @paulray are good.  Might be good for @demorest  to take a peek as well.

**Comment by paulray** [comment]
I agree that it looks good.  Nice to see a test included!

**Comment by luojing1211** [comment]
This looks good, I will merge it.

**Pull request merged**
