### PR TITLE
Run tests in parallel

### PR DESCRIPTION
**Pull request by abhisrkckl**
Github runners now provide multiple cores. 
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

Our tests can be sped up significantly if we run them in parallel.

### CODE REVIEW

**Comment by abhisrkckl** [comment]
The test failures seem to be due to `astropy` cache issues. #1374 may be a solution.

**Comment by abhisrkckl** [comment]
Here is a summary of what I am doing:
1. Parallelize tests using `pytest-xdist`. I am using 6 processes here. This is greater than the number of CPU cores available (4), but that's OK because many of our tests are IO-limited rather than CPU-limited. I am getting ~4-5x improvement in test execution time.
2. Re-run failed tests using `pytest-rerunfailures`. This handles intermittent failures that occur due to random chance.
3. In the macos test, `test_toa_selection.py` keeps failing in the parallel mode (but is OK when run serially). So I am running that test serially and everything else parallelly for macos.

**Comment by dlakaplan** [comment]
This is good.  I remember we had tried this a while ago but for some reason didn't implement it in CI.  But I don't see any reason not to.  Even a factor of ~2 change helps.

Is this ready to merge?

**Comment by abhisrkckl** [comment]
Yes

**Pull request merged**
