### PR TITLE
Read The Docs integration

### PR DESCRIPTION
**Pull request by jellis18**
I have started to set up `PINT` for auto-generated docs using Read The Docs related to Issue #221. So far most of these docs are boilerplate and can be modified but the basics are there. These docs should build whenever we commit to the master branch (these settings can be changed I think).

This may take a few iterations to get all the integrations set up correctly but I wanted to start this PR to make you aware that I'm working on this.

When it all works we should only have modify the static content (i.e user guides, tutorials READMEs etc and the docs from the docstrings will be generated automatically).

I have also added a `Makefile` that is very useful for building and viewing the docs easily (as well as other things). You should just be able to run `make docs` and it will build the docs and open the html in your browser.

### CODE REVIEW

**Comment by jellis18** [comment]
OK, I had to do a few things to get it to work but it seems ok now. I made a temporary Read The Docs page for my fork and you can see what the auto-generated docs would look like [here](http://pint-dev.readthedocs.io/en/latest/index.html).

**Comment by paulray** [comment]
Thanks for getting that going, it looks good!

**Comment by jellis18** [comment]
@paulray, thanks. In terms of the implementation I think it is basically done. You and others just have to add static material that you want. We should also probably figure out a better way of listing the modules. There are various Sphinx options that we could explore...

**Comment by paulray** [comment]
Cool, then should we merge this so I, and others, can start editing?  Will the docs show up at pint.readthedocs.io?

I noticed that the docs mention being able to `pip install pint`.  Sadly this won't work because of a namespace conflict in PyPI (see #33).

**Comment by jellis18** [comment]
> Cool, then should we merge this so I, and others, can start editing? Will the docs show up at pint.readthedocs.io?

They should show up at http://nanograv-pint.readthedocs.io/en/latest/, I had to use this name because pint was already taken. I also have a label in the github README like the travis label. We can put links in the README too.

>I noticed that the docs mention being able to pip install pint. Sadly this won't work because of a namespace conflict in PyPI (see #33).

OK, as I said a lot of the docs are boilerplate and will have to updated to `PINT` specifics. For example the contributing page is probably decent but should involve some more `PINT` specific stuff.

With that said I'm fine with merging, although we should probably do a squash and merge so we don't get the intermediate commits in the history.

**Comment by paulray** [comment]
Hmm. I never squash my PRs, so they are filled with all my ugly intermediate commits! :-)

**Comment by jellis18** [comment]
@paulray, well in some cases I think it is good so we don't have things like "Trying again" as commit messages ;)

**Comment by jellis18** [comment]
Should we merge this?

**Pull request merged**
