### PR TITLE
Add HAWC

### PR DESCRIPTION
**Pull request by dlakaplan**
Email from spokesperson:

> Latitude and Longitude:
> 18° 59' 41.63 ± 1.63" N, 97° 18' 27.39 ± 1.71" W
> 18.9949 ± 0.0005, -97.3076 ± 0.0005
> 
> The detector is 5 arc seconds wide. 
> 
> We use GPS for time stamp: https://arxiv.org/pdf/1410.6681.pdf
> ...
> Yes, WGS84 Easting, Northing, and Altitude: 678150 ± 50 m, 2101120 ± 50 m, 4096 m, Zone 14

### CODE REVIEW

**Comment by dlakaplan** [comment]
Looks OK to me (no obvious sign errors etc):
pint_observatories

**Comment by paulray** [comment]
Great!

**Comment by abhisrkckl** [comment]
Requested in #1171

**Comment by abhisrkckl** [comment]
Can this be merged? It looks good to me.

**Comment by dlakaplan** [comment]
I think it's fine.  They said they are synced to GPS so I said:
```
"include_bipm": false,
         "include_gps": true,
```
Is that the way to implement that?

**Comment by dlakaplan** [comment]
@abhisrkckl : after merging in your other PR now this is failing CI.  Issues with `numpy.typing` I think.  Can you investigate?

**Comment by dlakaplan** [comment]
I think this is fine to merge.  If we've gotten some of the clock details wrong we can figure that out with some data.

**Pull request merged**
