### PR TITLE
Custom type definitions

### PR DESCRIPTION
**Pull request by dlakaplan**
In `__init__.py` defining:
```
# Something that is a Quantity or can behave like one (with units assumed)
quantity_like = Union[float, np.ndarray, u.Quantity]
# Something that is a Time or can behave like one
time_like = Union[float, np.ndarray, u.Quantity, time.Time]
file_like = Union[str, Path, IO]
```
that can be used elsewhere (instead of exhaustively repeating those).

### CODE REVIEW

**Comment by dlakaplan** [comment]
#1709

**Comment by dlakaplan** [comment]
Are there other types to add? Or is this sufficient to get started?  And should those type definitions by in the top-level `__init__.py` or elsewhere?

**Comment by abhisrkckl** [comment]
I think these are good enough to start with. We can add more as needed.

**Comment by dlakaplan** [comment]
OK, probably ready to merge then.  This will simplify a few other in-process PRs.

**Pull request merged**
