### PR TITLE
Tiny change

### PR DESCRIPTION
**Pull request by paulray**
Just doing this to see what happens. Travis-ci works fine on my fork. Why is it failing on nanograv/master?

### CODE REVIEW

**Comment by paulray** [comment]
@luojing1211 @scottransom  This fixes the travis-ci issue by bumping the version of Ubuntu used by travis-ci from xenial to bionic.  I'm not an Ubuntu user, but I think most people are moving that way now, right?

**Comment by scottransom** [comment]
Maybe?  But a lot of workstations and/or clusters which are maintained by others use older versions of things.  Do you know why this test was failing?  Once again, it seems like maybe it isn't a good test.

**Comment by paulray** [comment]
Here is the error. I don't think the test is bad, it is just looping over several ephemeris files and computing the position of things using jplephem. I don't know why it is getting the buffer too small error. It only happens on xenial with Python 3.7, not 3.6 or 3.8.  Since it goes away when the version is bumped, I'm happy to ignore it.  If someone wants to run this test on a local machine with xenial and Python 3.7, that might be interesting, but I don't have a machine like that.

```
_____________________ TestSolarSystemDynamic.test_earth _______________________
self = <test_solar_system_body.TestSolarSystemDynamic testMethod=test_earth>
    def test_earth(self):
        for ep in self.ephem:
>           a = objPosVel_wrt_SSB("earth", self.tdb_time, ephem=ep)
/home/travis/build/nanograv/PINT/tests/test_solar_system_body.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pint/solar_system_ephemerides.py:232: in objPosVel_wrt_SSB
    pos, vel = coor.get_body_barycentric_posvel(objname, t)
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/astropy/coordinates/solar_system.py:337: in get_body_barycentric_posvel
    return _get_body_barycentric_posvel(body, time, ephemeris)
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/astropy/coordinates/solar_system.py:292: in _get_body_barycentric_posvel
    spk.generate(jd1, jd2)):
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/jplephem/spk.py:219: in generate
    self._data = data = self._load()
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/jplephem/spk.py:177: in _load
    init, intlen, rsize, n = self.daf.read_array(self.end_i - 3, self.end_i)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <jplephem.daf.DAF object at 0x7fce0b394828>, start = 4047265
end = 4047268
    def read_array(self, start, end):
        """Return floats from `start` to `end` inclusive, indexed from 1.
    
        The entire range of floats is immediately read into memory from
        the file, making this efficient for small sequences of floats
        whose values are all needed immediately.
    
        """
        f = self.file
        f.seek(8 * (start - 1))
        length = 1 + end - start
        data = f.read(8 * length)
>       return ndarray(length, self.endian + 'd', data)
E       TypeError: buffer is too small for requested array
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/jplephem/daf.py:147: TypeError```

**Comment by scottransom** [comment]
I was thinking that xenial was 18.04, but it is actually 16.04 (i.e. from 2016).  Given that, I think that you can probably bump the travis OS version.  However, the error seems like it might be related to a problem with jplephem.  Array allocation certainly doesn't seem like it should be something that we are worrying about as users (although maybe we are doing the allocation incorrectly?)

**Comment by scottransom** [comment]
And read_array() looks correct to me....  hmmm.

**Comment by luojing1211** [comment]
Just did a search on the astropy and jplephem repo. I did not find any report for this issue.

**Comment by paulray** [comment]
Maybe 16.04 isn't even supported anymore?
Anyway, I'm not spending more time on this since I can't reproduce the issue.
Merging...

**Pull request merged**
