### PR TITLE
Fitter error checking

### PR DESCRIPTION
**Pull request by aarchiba**
Verify and improve the error checking in WLSFitter (ideally others too) so that most cases of parameter degeneracy can be reported.

### CODE REVIEW

**Comment by aarchiba** [comment]
Still to do: there's an xfail on DMX bins that don't contain anything.

**Comment by aarchiba** [comment]
There's some numerical stability complications, so that in order to keep passing tempo2 compatibility tests I had to largely disable it for GLS-based fitters, including the Wideband. They will still detect parameters that don't do anything, and the PR also includes explicit checking of DMX bins and mask parameters. You can call `fit_toas` with `threshold=1e-14` to gain numerical stability and also be notified of degeneracies (in any Fitter).

**Comment by aarchiba** [comment]
Please take a look, but I think this is ready to merge.

**Comment by pennucci** [comment]
I just tried it on some data where the DMX ranges don't match to the data, and it certainly tells me so (listing all the DMX ranges...!).

**Comment by aarchiba** [comment]
Automated code could catch the exception, which contains a list of the problematic DMX ranges (or mask parameters) and so could automatically freeze or remove them.

**Comment by aarchiba** [comment]
Ready to go.

**Pull request merged**
