### PR TITLE
Update requirements for oldestdeps

### PR DESCRIPTION
**Pull request by paulray**
I updated the version of scipy used for the oldestdeps tests to a version released just before our numpy version 1.18.5. This constraint keeps it from installing a very new scipy, which pulls in a new numpy that causes crashes in the oldestdeps tests. So this bumps up the scipy minimum required version to 1.4.1.

### CODE REVIEW

**Comment by paulray** [comment]
Fixes #1401 (again).  Should solve issue seen in #1482

**Comment by paulray** [comment]
Oldestdeps now passes. This can be merged as soon as someone else takes a look. The only significant change is updating the minimum version of scipy to 1.4.1.  Actually, I'll add a changelog entry and push that now.

**Comment by paulray** [comment]
OK, I botched, then fixed, the CHANGELOG merge. It should be good to go now

**Comment by dlakaplan** [comment]
Those are pretty big bumps to the `scipy` and `matplotlib` versions.  `scipy` 1.4.1 is from Dec 2019, and `matplotlib` 3.2.0 is from March 2020.  But I guess in both cases those are consistent dates with our `numpy` requirement so they make sense.  So I can merge this unless anybody objects (or I can wait a day or two).

**Comment by dlakaplan** [comment]
And does adding the oldestdeps to the tox environments mean it will get tested more explicitly?

**Comment by paulray** [comment]
I'm not sure the effects of adding oldestdeps to the environments list. I don't know why it wasn't there before. I just noticed that `tox -l` didn't show the oldestdeps environment, which seemed wrong, so I added it.

**Pull request merged**
