### PR TITLE
Fix DECJ uncertainty more then 60 arcsecond problem

### PR DESCRIPTION
**Pull request by luojing1211**
This should fix the issue #297. But I am not sure if there is any parfile with DEC uncertainty in the format of '0:0:xx.xxxx'? 

@paulray Have you seen any parfile like this?

-Jing Luo

### CODE REVIEW

**Comment by paulray** [comment]
@luojing1211 I searched all 5713 .par files on my computer (from MANY different sources) and non of them use a DECJ uncertainty with ":" in it, so I think it should always be interpreted as a simple floating point number of arcseconds.

As a side note, Tempo2 often produces par files with DECJ errors that look like this:
```
DECJ           -45:10:34.81100  19099631298631109784835146042022771335484276116063150918714795143707197181702597070494097091739463025361450901761261876054083020794361316684857344.00000000000000000000
```
So, this kind of absurd number should at least not cause PINT to crash. I'm not sure if this bug in Tempo2 was ever fixed, but numbers like that are in many of my par files.

**Comment by luojing1211** [comment]
So right now. PINT takes the absurd number, but it would not keep the precision. If you think this change is ok. We can merge it.

**Comment by paulray** [comment]
Why is only one line changed?  The same issue should apply to RAJ as well, where uncertainty is in seconds of hourangle and numbers >60 should also be allowed.

**Comment by luojing1211** [comment]
The RAJ uncertainty is in the unit of hourangle seconds. I did not find an astropy unit match this propose. One I can think of is arcsecond/15.0 as unit. But it will not add to the quantity with a unit of hourangle. What do you think? Should we just define the unit of hourangle second?

**Comment by paulray** [comment]
I'm not sure. It sounds reasonable to define the unit hourangle second.

**Comment by luojing1211** [comment]
@paulray I changed the RAJ uncertainty unit to newly defined `hourangle_second`. It should be able to fix the problem. As long as the uncertainty is constantly in the unit of hourangle seconds with the format of a numerical value, it should work.

**Comment by luojing1211** [comment]
Hi @paulray, can we merge this. I would not like a PR getting too big.

**Comment by paulray** [comment]
Can you stick in a unit test to show that both cases work with the uncertainty greater than 60?

**Pull request merged**
