### PR TITLE
WIP: find and resolve DMJUMP uncertainty anomalies

### PR DESCRIPTION
**Pull request by aarchiba**
@pennucci reports some fits involving `DMJUMP` parameters wind up with improbably large uncertainties on them. The intention here is to resolve these.

### CODE REVIEW

**Comment by aarchiba** [comment]
Unfortunately to date I haven't been able to reproduce them - see test case.

**Comment by pennucci** [comment]
I checked the test case, and I see it passes.  But if you use the `tim_all` TOAs and the `par,` it 'fails', even though the `assert_allclose` is still reasonably close.  Still, in the examples I've seen, I wonder if it has something to do with DMX and/or regular JUMPs.

**Comment by pennucci** [comment]
#933 is in process of fixing this in part.

**Comment by luojing1211** [comment]
Since the DMJUMP is fixed, can we close this PR?

**Comment by aarchiba** [comment]
Do we now have test cases that verify that it is fixed? Have we solved all the problems?

**Comment by luojing1211** [comment]
We have some test case about the DMJUMP derivative, which leads to this problem.

**Comment by aarchiba** [comment]
I think this may be fixed by #1047 ? In any case we can revive it if a bug is filed.

**Pull request closed without merging**
