### PR TITLE
Dmxparse update

### PR DESCRIPTION
**Pull request by bshapiroalbert**
Requests for updates to dmxparse function from #672 have been included. The changes are as follows:
1. If there is no covariance_matrix attribute, the function will return the mean subtracted dmx values from the initial `fitter.model` as well as the initial errors from `fitter.model`. It will also print a warning that it is doing so (let me know if you'd like the warning to say something else). If there are no errors, then the DMX_vErrs should be a list of `None`'s. 
2. The DMX bins do not need to be in any particular order, and the number of values in the index of the DMX bin should not matter, e.g. DMX_0001, DMX_0002, DMX_0004 will be parsed appropriately, and DMX_01, DMX_02, DMX_04 should also work.

### CODE REVIEW

**Comment by paulray** [comment]
I hate to ask one more thing, but since you are working on the code...

I think it would be more "PINT-like" to have the arrays returned include units on them. I think this is a tiny change. Since you grab the values as par.value, when you are building the dictionary of arrays to return, you can just multiply each by the appropriate par.unit.

**Comment by bshapiroalbert** [comment]
Sound good @paulray, I'm fine with that. I'll add that in soon.

**Comment by bshapiroalbert** [comment]
I've updated the `dmxparse` function so that if you put in a model that does not have any DMX bins in it, it will throw a Runtime error saying that's why it's failing. I have also (I think) figured out how to get the function to run if a few DMX bins are not fit for as discussed by @paulray. The returned values on the errors in this case in the array are nan, and if you print the results to the output file it also prints nan. It will also tell you if there are any bins that are not fit for, and that it's doing the appropriate masking. I also added an additional test for some of this coverage. It passed all the tests I could think of that seemed plausible. Let me know if anybody has any comments on this or finds a way to break it that I haven't thought of.

**Comment by paulray** [comment]
I tried a couple of my problem cases and it worked great. Thanks for the fixes! I think I'll merge this.

**Comment by bshapiroalbert** [comment]
Sounds great! Let me know if you find other ways it needs to be improved.

**Pull request merged**
