### PR TITLE
Improve test coverage

### PR DESCRIPTION
**Pull request by abhisrkckl**
Other changes:
1. Bug fix in `compare_t2_observatories_dat` and `compare_tempo_obsys_dat`
2. sourcery

### CODE REVIEW

**Comment by abhisrkckl** [comment]
This is relatively minor and ready to go.

**Comment by dlakaplan** [comment]
How do your tests work on headless system?  Does specifying the backend mean they will work anywhere?

**Comment by dlakaplan** [comment]
Can you explain why you had to put stuff in `tests/datafile/observatory/`?

**Comment by abhisrkckl** [comment]
> Can you explain why you had to put stuff in tests/datafile/observatory/?

The two functions `compare_t2_observatories_dat`  and `compare_tempo_obsys_dat` compares the PINT observatory information against tempo2/tempo observatory files. The files I copied to tests/datafile/observatory/ are the tempo2 and tempo observatory files to do this comparison.

**Comment by abhisrkckl** [comment]
> How do your tests work on headless system? Does specifying the backend mean they will work anywhere?

As I understand it, the "Agg" backend only supports writing files and does nothing when `plt.show()` is called.

**Comment by dlakaplan** [comment]
> > How do your tests work on headless system? Does specifying the backend mean they will work anywhere?
> 
> As I understand it, the "Agg" backend only supports writing files and does nothing when `plt.show()` is called. So it should work on a headless system. I have tried this on an `ssh` session without X forwarding and it works.

OK, good.

**Comment by dlakaplan** [comment]
> > Can you explain why you had to put stuff in tests/datafile/observatory/?
> 
> The two functions `compare_t2_observatories_dat` and `compare_tempo_obsys_dat` compares the PINT observatory information against tempo2/tempo observatory files. The files I copied to tests/datafile/observatory/ are the tempo2 and tempo observatory files to do this comparison.

How did this work before you copied those?

**Comment by abhisrkckl** [comment]
> How did this work before you copied those?

These functions were broken before and did not have any tests. That is why these files were not present before.

**Comment by dlakaplan** [comment]
> > How did this work before you copied those?
> 
> These functions were broken before and did not have any tests. That is why these files were not present before.

Ah, OK.

**Pull request merged**
