### PR TITLE
Fix missing files test to handle unset TEMPO2 variable

### PR DESCRIPTION
**Pull request by aarchiba**
Straighten out annoying file not found error that makes tests fail.

### CODE REVIEW

**Comment by paulray** [comment]
Maybe add the astropy>=3.2 to requirements.txt to this PR as well?

**Comment by aarchiba** [comment]
> Maybe add the astropy>=3.2 to requirements.txt to this PR as well?

That's a tiny PR so I'd rather keep it separate. But yes it should absolutely go in. (Maybe before I manage to fix all the bugs I put in this one...)

**Comment by aarchiba** [comment]
I sort of think we should have whole categories of tests that are run whenever tempo or tempo2 are found to be installed. I don't know that we can put them in Travis - automatedly installing tempo and tempo2 may not be feasible - but at least some of our users will have them, and systematically running these tests would help catch some of our mistakes. 

In fact I think we have some of these but they're under "validation" and not run?

**Comment by aarchiba** [comment]
Fixes #497

**Comment by luojing1211** [comment]
We have some Tempo2 generated results saved in the test_data directory. The
validate is not a part of our Travis test.
-Jing

**Comment by aarchiba** [comment]
> We have some Tempo2 generated results saved in the test_data directory. The validate is not a part of our Travis test. -Jing

Yes, I saw that. I bet many of those tests now fail, since we're not running them.

I would like to see an adapter through which we could run tempo/tempo2 that cached the results. Then we could check in the results to git, and regenerate them on a machine that does have tempo/tempo2 whenever we expect those results to change. On a machine without tempo/tempo2, the tests would just pull in the cached results and do the comparison. Using the wrapper would make it easy to write the tests, running tempo/tempo2 as needed.

**Pull request merged**
