### PR TITLE
Fix random_models.py

### PR DESCRIPTION
**Pull request by champagne-cmd**
Updated random_models.py to use new covariance matrix machinery. Fixes issue #848 where random models didn't work properly with the DM parameter.
One thing to discuss: Should random_models.py be collapsed into the new calculate_random_models in utils.py? The random_models.py returns time residuals, while the calculate_random_models returns phase residuals.

### CODE REVIEW

**Comment by aarchiba** [comment]
> Updated random_models.py to use new covariance matrix machinery. Fixes issue #848 where random models didn't work properly with the DM parameter.
> One thing to discuss: Should random_models.py be collapsed into the new calculate_random_models in utils.py? The random_models.py returns time residuals, while the calculate_random_models returns phase residuals.

Can you describe the differences between them? If that's the only difference then conversion is so easy I don't think both functions should exist. If there are more differences then perhaps it makes sense to integrate them into one function that can do both.

**Comment by aarchiba** [comment]
Do you have tests that verify that this works now? Even just running it at all would be a help.

**Comment by scottransom** [comment]
I talked to @clp3ef about this a bit, but I don't think she has had a chance to look into it.  But the codes are really similar, and do almost identical things.  So I certainly think that both places could use the new code.

**Comment by aarchiba** [comment]
A simple test would be structural - hand it a timing model and a set of TOAs and ensure that the result was the right shape and had the right units. 

A more sophisticated could take a simple model with F0 and F1 and no correlation and check the random residuals against pen-and-paper uncertainties at various times. One could check that the results were within five sigma, or check that the mean and standard deviation of a modest sample were roughly right. (The latter would require some modest statistical deviousness, and any random operation should take a random seed or random state object for test repeatability.)

**Comment by aarchiba** [comment]
Discussion says: absolutely combine the two. Is it possible for them to generate (lists of) Residuals objects? That would ensure that the conversion between time and phase was handled as well as we know how.

**Comment by champagne-cmd** [comment]
It seems importing the Residuals class in utils.py creates a circular import as residuals.py imports `weighted_mean` from utils.py. So not sure if we can create a list of residual objects within calculate_random_models. I will go ahead and try to implement the input for choosing phase or time resid, and if another solution presents itself we can discuss and modify.

**Comment by champagne-cmd** [comment]
There is something I'm a little puzzled by. In random_models.py, two fake toa objects are created:
```
x = toa.make_fake_toas(
        minMJD - spanMJDs * ledge_multiplier,
        maxMJD + spanMJDs * redge_multiplier,
        npoints,
        mrand,
    )
x2 = toa.make_fake_toas(minMJD, maxMJD, npoints, mrand)
```
and the second fake TOAs object is only used like so:
```
rs = mrand.phase(x, abs_phase=True) - fitter.model.phase(x, abs_phase=True)
rs2 = mrand.phase(x2, abs_phase=True) - fitter.model.phase(x2, abs_phase=True)
# from calc_phase_resids in residuals
rs -= Phase(0.0, rs2.frac.mean() - rs_mean)
```
The comment says "from calc_phase_resids in residuals", but I'm a little lost why two TOAs objects are used or the best way to incorporate this into calculate_random_models, as that method only uses one fake TOAs object.

**Comment by aarchiba** [comment]
I have to say I would have just implemented this by jittering the model and computing Residuals objects for each jittered version of the model. That would only need one set of TOAs, whether real or fake, at which to show the effect of model changes. But this method seems to work, though I don't understand what it would mean to subtract phases evaluated at different times. The issue may be getting the constant offset right?

**Comment by paulray** [comment]
> It seems importing the Residuals class in utils.py creates a circular import as residuals.py imports `weighted_mean` from utils.py. So not sure if we can create a list of residual objects within calculate_random_models. I will go ahead and try to implement the input for choosing phase or time resid, and if another solution presents itself we can discuss and modify.

Does this method help? https://stackoverflow.com/questions/22187279/python-circular-importing

**Comment by aarchiba** [comment]
This does highlight a problem with PINT: PINT's TimingModels can capture parameter uncertainties but not parameter correlations. So we need a Fitter here just for the covariance matrix.

**Pull request closed without merging**
