### PR TITLE
add **kwarg to get_toas()

### PR DESCRIPTION
**Pull request by luojing1211**
This PR enables the **kwarg functionality of get_toas() function.

### CODE REVIEW

**Comment by luojing1211** [comment]
@scottransom @demorest @paulray, Do you think this PR will create any problems?

**Comment by paulray** [comment]
What does it do?  Are the kwargs used somehow?

**Comment by luojing1211** [comment]
It allows the users to pass the optional parameters as a dictionary.

**Comment by demorest** [comment]
You don't need `kwargs` to pass optional parameters via a dictionary.  You can use the `**` operator, for example this works fine in current PINT:
```
params = {'ephem':'DE435', 'include_gps':False}
toas = pint.toa.get_TOAs('J0613-sim.tim',**params)
```
What `kwargs` does is let you pass keyword params with names that are not in the list of standard parameters.  Without `kwargs` this raises a "got an unexpected keyword argument" error.

I don't really understand what this PR is intended to accomplish.  Jing, can you describe a bit more?  Unless we have a specific need for it, I guess it seems better to me to not use `kwargs` here because it will suppress errors in cases where there is a typo in a paramer name, etc.

**Comment by luojing1211** [comment]
I did not know the **operator can be used like that way. I guess my problem is solved and close the PR.

**Pull request closed without merging**
