### PR TITLE
[WIP] Verbosity fix 

### PR DESCRIPTION
**Pull request by almcewen0**
per issue https://github.com/nanograv/PINT/issues/984, I have adjusted the verbosity of a few of the components. This includes:

changing language when components are boolean
reducing log level from WARNING to INFO for START/FINISH/CHI2/NTOA
including these logger statements only when in "max" verbosity level
If there are other parameters that should be reported less/more often, or if there are parameters that would be better suited for different INFO/WARNING language, please comment those parameters and changes here.

### CODE REVIEW

**Comment by almcewen0** [comment]
I just attempted to blacken this code, and I got the following error:

error: cannot format src/pint/models/timing_model.py: cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line 82)
Oh no! 💥 💔 💥
1 file failed to reformat.

i've never seen this before. do any of you have any idea what's up?

**Comment by scottransom** [comment]
Looks like there is a syntax error on line 82.  Did you modify that line?

**Comment by scottransom** [comment]
Note that black runs fine on the latest checkout of timing_model.py.  So it must be some change in your local file (maybe accidental).

**Comment by almcewen0** [comment]
> Looks like there is a syntax error on line 82. Did you modify that line?

nope. and it doesn't show up in the modified files. hmm...

**Comment by aarchiba** [comment]
Is it possible there's a merge conflict? Lines full of `<<<<<<<<` or `>>>>>>>>` make black very unhappy.

**Comment by paulray** [comment]
And is your black, version 20.8b1?

**Comment by almcewen0** [comment]
> Is it possible there's a merge conflict? Lines full of `<<<<<<<<` or `>>>>>>>>` make black very unhappy.

Nope, but i see that i am using version 19.10b0, so that might be the problem (good catch, @paulray)

**Comment by almcewen0** [comment]
my version is 19.10b0, but it seems like I cannot update it. i'm working in a conda environment and when I use `conda update black`, it says it is fully up to date, with version 19.10b0. i know this is a bit outside the scope of this MR, but is there something I am missing here?

**Comment by almcewen0** [comment]
okay, so the black issue isn't resolved, but i found that there was a tab/spaces issue somewhere. so now I can work on getting the model names implemented. for that reason, i'm gonna mark this as WIP, because it will need https://github.com/nanograv/PINT/pull/987 to be merged

**Comment by paulray** [comment]
Now that #987 is merged, can this be too?

**Comment by almcewen0** [comment]
@paulray yes, i think so - though I dunno if I can OK my own PR.

**Pull request merged**
