### PR TITLE
Add WAVE parameters

### PR DESCRIPTION
**Pull request by matteobachetti**
This PR adds WAVE parameters (Resolves Issue #381 ).
I had to invent a new kind of parameter, that takes a pair of floats.
I don't know if the logical steps I did are all correct, so I would like some feedback to get this right. I tried the WAVE function on a local notebook and it seems to be doing the right thing, but I'm not sure this is still the case after I plug it into PINT.

### CODE REVIEW

**Comment by paulray** [comment]
@luojing1211 having WAVE parameters in PINT would be great. Can you take a look at this and see if it looks good, or if you have suggested changes before merging?

**Comment by luojing1211** [comment]
@matteobachetti, Can you rebase your PINT branch against the PINT master branch?

**Comment by matteobachetti** [comment]
@luojing1211 Sorry for the late reply, I'm on vacation. I will try asap

**Comment by matteobachetti** [comment]
@luojing1211 rebased.

**Comment by matteobachetti** [comment]
@paulray there are tests failing. one seems to imply that TOAs class doesn't have the `ntoas` attribute anymore? Others seem unrelated instead. Do you have pointers?

**Comment by luojing1211** [comment]
TOAs class should have it. But in the old API, we are passing TOAs.table
into the delay or phase function. Perhaps we need to check if there is any
place using the old API.

-Jing

**Comment by paulray** [comment]
Yes, this is all due to the changed API.
You should now call `delay()` with a TOAs object, rather than TOAs.table
In your wave_delay you'll need to use `toas.table['tdbld']` instead of just `toas['tdbld']`

**Pull request merged**
