### PR TITLE
Fix RAJ, DECJ uncertainties and a couple other bugs

### LINKED ISSUE #664: Incorrect uncertainties on RAJ, DECJ?
I've been working with PINT and was making a pretty-printer for the results of a fit. In doing so I found that the uncertainties reported on RAJ and DECJ are VERY different than Tempo2, by many orders of magnitude. Something is wrong.  Attached here is a little notebook that fits the data in pint/examples and looks at the uncertainties, compared to a Tempo2 fit of the same.  
(You will have to change the paths and delete the .print_summary() cell if you want to re-run it since that is only in my branch).

To summarize here, tempo2 gives:
```
PARAMETER       Pre-fit                   Post-fit                  Uncertainty   Difference   Fit
---------------------------------------------------------------------------------------------------
RAJ (rad)       1.63071752883066          1.63071752883548          8.8177e-11    4.8146e-12    Y
RAJ (hms)       06:13:43.9756752           06:13:43.9756753         1.2125e-06    6.6205e-08   
DECJ (rad)      -0.0351355401430826       -0.0351355400811907       1.7101e-10    6.1892e-11    Y
DECJ (dms)      -02:00:47.22538           -02:00:47.22537           3.5273e-05    1.2766e-05   
```

PINT gives compatible fitted values, but the RAJ uncertainty is 2.4e-14 rad and the DECJ uncertainty is 4.6e-14 rad.

Any ideas?

[PositionTest.ipynb.zip](https://github.com/nanograv/PINT/files/4496886/PositionTest.ipynb.zip)

### PR DESCRIPTION
**Pull request by paulray**
This is a small patch to fix #664 

This is the way to do it if you want to leave the parameters with different units for `par.quantity` and `par.uncertainty`

As discussed in the #664 thread, the alternative is to change the units of par.uncertainty to be the same as the parameter.

### CODE REVIEW

**Comment by paulray** [comment]
Since this PR is still open, I added a fix for #668

**Comment by paulray** [comment]
This is just a few lines of changes and fixes 2 bugs. @luojing1211 @scottransom @demorest are you OK merging this?

**Comment by scottransom** [comment]
Fine with me.  I'd really like to see the uncertainty unit issue cleaned up as well, though (including fixing the 1e-12 thing for PBDOT).  But until then, I agree these should go in.

**Comment by paulray** [comment]
OK, I think I fixed PBDOT scaling with the last commit.  It should scale PBDOT properly upon reading but the PBDOT Quantity will always have units that are not scaled.

**Comment by paulray** [comment]
This should also fix #597

**Comment by paulray** [comment]
To show an example like that pointed out in #597, this now works correctly.
I added this line to J0613-sim.par:
`PBDOT 7`
```
In [2]: m = pint.models.get_model("J0613-sim.par")                                                                                            
INFO: Parameter PBDOT's value will be scaled to 1e-12  [pint.models.parameter]

In [3]: m.PBDOT                                                                                                                               
Out[3]: floatParameter( PBDOT           7e-12             () frozen=True)

In [4]: m.PBDOT.quantity                                                                                                                      
Out[4]: <Quantity 7.e-12>

In [5]: m.PBDOT.value                                                                                                                         
Out[5]: 7e-12

In [7]: import astropy.units as u                                                                                                             

In [8]: m.PBDOT.quantity.to(u.dimensionless_unscaled)                                                                                         
Out[8]: <Quantity 7.e-12>

In [9]: m.PBDOT.quantity.to(u.dimensionless_unscaled).value                                                                                   
Out[9]: 7e-12

```

**Comment by scottransom** [comment]
sweet.....  :-)

**Comment by paulray** [comment]
Oops, last commit is not just a typo fix. It cleans up a bit of cruft that is not needed now that a parameter's units aren't actually modified when scaling is done. Just the value is scaled.

**Comment by luojing1211** [comment]
@paulray, why the commit number is so big. Is this rebased to the master?

**Comment by paulray** [comment]
Yes, I merged in the master branch

**Comment by luojing1211** [comment]
I see. That is why my commits on the add_components show here.

**Comment by paulray** [comment]
I also just added another commit that fixes the Powell fitter.  
@scottransom this is a strange one.  It was caused by `fitter.set_params()`.
It is called with a dictionary of keys and values. Normally the values are all floating point numbers. For some reason on like the 10th call to set_params() in the Powell fitter, the values change to Quantity (but dimensionless).  This causes par.value = v to barf.  So I added code to `fitter.set_params()` to check if the values were Quantities and use v.value in that case.

Strange but it works.  My only concern is that there could be a performance penalty if set_params is called many times by some fitters.

**Comment by paulray** [comment]
This now also fixes #665

**Comment by scottransom** [comment]
@paulray I remember seeing that before with early tests of the Powell fitter.  It must be some strange conditional part of a loop in the Scipy routine.  Very bizarre....

**Comment by paulray** [comment]
Bizarre indeed. Since this PR fixes a bunch of bugs now, I'm merging it so future work can be based of this. I think we are very close to ready to tag 0.7!

**Pull request merged**
