### PR TITLE
Allow PINT to write clock correction files

### PR DESCRIPTION
**Pull request by aarchiba**
PINT is already able to read in clock correction files in either TEMPO or TEMPO2 format. This PR allows PINT to write out clock correction files in either format, optionally combining multiple clock correction files (for example ao2gps + gps2utc). This enables conversion of clock files between formats as well as conversion of other suitable information into clock files.

As it currently stands, the "merging" of clock files means combining them by adding the corrections from the included clock correction files. This is distinct from splicing together clock correction files that cover different intervals; that's a different problem.

When reading, writing, and merging clock correction files, comments are preserved. This allows comments at the beginning of the file, comments on clock correction lines, and comments following a clock correction. (Comments on their own line are associated with the previous clock correction.)

This allows more or less lossless conversion between TEMPO and TEMPO2 clock correction file formats, and is used by the global clock corrections [repository](https://nanograv.github.io/pulsar-clock-corrections/status.html) for this purpose.

### CODE REVIEW

**Comment by aarchiba** [comment]
> Does this keep comments? There is along history of clock correction files having comments about why things changed and then those getting lost in various conversions etc.

PINT does not currently record comments at all upon reading clock files. I had in mind that this would be used only for disposable temporary clock files with comments indicating that they were auto-generated. Some form of comment preservation could be added.

**Comment by scottransom** [comment]
Probably not super necessary given that I think most of the comments in current clock files are for the archival corrections (meaning long ago).  Although I do see that they could be useful even now and in the future (i.e. the big step in the GBT corrections that I *think* is due to maser maintenance).

**Comment by aarchiba** [comment]
Now preserves comments on read/write in both TEMPO and TEMPO2 formats. Needs more testing. Also merging discards comments (and it shouldn't! or at least not necessarily).

**Comment by aarchiba** [comment]
Also worth thinking about: do we implement the TEMPO `f` flag (treat as a fixed measurement, do not interpolate)? Not fundamentally hard, just turn it into two corrections at the beginning and end of the constant time.

**Comment by dlakaplan** [comment]
Is this ready to merge?  Were there any pending items from our meeting?

**Comment by aarchiba** [comment]
I think we concluded this was ready to go.

**Pull request merged**
