### PR TITLE
Getattr cleanup

### LINKED ISSUE #828: TimingModel objects produce and suppress RecursionError while being copied
The `__getattribute__` machinery in TimingModel objects interacts with `copy.deepcopy` in such a way that RecursionErrors are generated. This is suppressed by a bare `except` in `TimingModel.__getattr__`. The bare `except` has the side effect of making any exception in a property look like a missing attribute, so this causes other problems, in addition to the wastefulness of running the stack twenty levels deep or whatever Python's limit is. This can be triggered by `tests/test_fitter.py`.

With a custom warning added I can display:
```
tests/test_fitter.py::test_fitter
tests/test_fitter.py::test_ftest
  /home/archibald/projects/pint/PINT/src/pint/models/timing_model.py:222: UserWarning: Exception <class 'RecursionError'> maximum recursion depth exceeded while calling a Python object was raised in __getattr__(components)
    warnings.warn("Exception {} {} was raised in __getattr__({})".format(type(e), e, name))
```

### PR DESCRIPTION
**Pull request by aarchiba**
Remove `__getattr__` from Component objects, and clean up `__getattr__` implementation on TimingModel.

Fixes #828 .

### CODE REVIEW

**Comment by aarchiba** [comment]
Incidentally fixes a few bugs that happen when not using barycentric frequencies in DM calculations.

**Comment by aarchiba** [comment]
Documentation to explain TimingModel: https://pulsar-pint.readthedocs.io/en/getattr_cleanup/api/pint.models.timing_model.html#pint.models.timing_model.TimingModel

**Comment by luojing1211** [comment]
The `TimingModel` can act as a dictionary now? This is quite neat.

**Comment by aarchiba** [comment]
Ah, no, sorry, I misunderstood, you use the `.components` property to get dictionary access to components by name. It would be straightforward to add dictionary-style access to TimingModels so you could access either Parameters or Components or both. Parameters are tempting because at the moment you need to use `getattr(model, p)` to get at them.

**Comment by scottransom** [comment]
Once this passes Travis, this should be ready to merge, right?

**Comment by aarchiba** [comment]
Yes, should be working and uncontroversial (bug fix, API change discussed on telecon).

**Comment by aarchiba** [comment]
Merge of one of the other PRs added a test that reveals a change I missed. Will get to this.

**Pull request merged**
