### PR TITLE
Mixed wideband + narrowband TOAs objects should not be allowed.

### PR DESCRIPTION
**Pull request by abhisrkckl**
Raise an exception in the case of a tim file with mixed narrowband and wideband TOAs.

### CODE REVIEW

**Comment by dlakaplan** [comment]
Is a warning rather than an exception appropriate here?  Can PINT actually do a sensible fit with only a fraction of data being WB?

**Comment by abhisrkckl** [comment]
> Can PINT actually do a sensible fit with only a fraction of data being WB?

I don't think so. AFAIK, Tim Pennucci's papers as well as the NG12.5 paper, where the WB fitting formalism are given, assume that all the TOAs should be wideband. I am not sure if anyone has worked out how to accurately mix narrowband and wideband toas.

**Comment by dlakaplan** [comment]
It looks like this would work for `get_toas` and `get_model_and_toas`.  Can you confirm?

**Comment by abhisrkckl** [comment]
Yes. get_model_and_toas calls get_toas under the hood. So this should work for both.

**Comment by dlakaplan** [comment]
Great.  Then I can probably merge whenever you want.

**Comment by abhisrkckl** [comment]
Yes. This is ready.

**Pull request merged**
