### PR TITLE
Wideband improvements

### LINKED ISSUE #851: DMJUMP fitting is not working
In some cases, just freeing the DMJUMP parameters and iterating appears stable, in others it goes off the rails.  Perturbing the DMJUMP parameters is similar.  In all cases, the uncertainties on the DMJUMP and DMX parameters become very large and all nearly identical (out to 7 or 8 decimal places).  So something is out of whack.

### PR DESCRIPTION
**Pull request by aarchiba**
This is exploring whether we can test and improve PINT's handling of wideband TOAs. It is intended to add, if the appropriate flags are present, the columns `dm` and `dme` to TOAs objects, and eventually everything that works with wideband TOAs should use those.

Will hopefully fix #851 .

### CODE REVIEW

**Comment by aarchiba** [comment]
I added some substantial doc improvements, in particular I made sure that WidebandTOAFitter was documented at all, and I clarified how to use WidebandTOAResiduals.

**Comment by aarchiba** [comment]
New documentation:

- Residuals: https://pulsar-pint.readthedocs.io/en/wideband_improvements/api/pint.residuals.html
- Fitter: https://pulsar-pint.readthedocs.io/en/wideband_improvements/api/pint.fitter.html

**Comment by paulray** [comment]
The documentation of `scaled_by_F0` is wrong. That is NOT intended to say whether time or phase residuals are being computed!  It is a setting for how time residuals are computed from phases in `calc_time_resids()`. The default is to do it the way TEMPO/Tempo2 do it and convert from phase to time using model.F0. This is usually a good approximation for many pulsars. However, for some pulsars the current F can be a long way from F0 because of large frequency derivatives. In this case, the conversion should be done using `get_PSR_freq(modelF0=False)` which is MUCH slower but returns the local frequency using `d_phase_d_toa`.

**Comment by aarchiba** [comment]
> The documentation of `scaled_by_F0` is wrong. That is NOT intended to say whether time or phase residuals are being computed! It is a setting for how time residuals are computed from phases in `calc_time_resids()`. The default is to do it the way TEMPO/Tempo2 do it and convert from phase to time using model.F0. This is usually a good approximation for many pulsars. However, for some pulsars the current F can be a long way from F0 because of large frequency derivatives. In this case, the conversion should be done using `get_PSR_freq(modelF0=False)` which is MUCH slower but returns the local frequency using `d_phase_d_toa`.

Good to know. But is that what the implementation does?

**Comment by pennucci** [comment]
Quick questions, not sure where to put these:
--Shouldn't the last line in `test_wideband_residuals` be `assert len(r.dm.dm_data) <= len(wb_toas)`, not strictly less than?
--Why in `test_wideband_residuals_dof` is the parameter `"DMJUMP"` set free?  Shouldn't it be `"DMJUMP1"`?  As an aside, is there a way to recover the condition each JUMP/DMJUMP parameter corresponds to?  i.e., how would someone stumbling upon `DMJUMP1` know that it corresponds to the selection `-fe L-wide`?
--The assertion in the test that fails, `test_wideband_fit_dmjump`, should look for -10 not 10 (same as you have it in `test_wideband_fit_dmjump_all`).  I know it currently fails because of not all TOAs having DMs, but as a hack, if you give each TOA an arbitrary DM and a really, really large DM uncertainty, then the test passes (checking DMJUMP1 == -10 within some reasonable atol).  I know this is not what the test is after, but it's a sanity check that it should work.

**Comment by aarchiba** [comment]
> --Shouldn't the last line in `test_wideband_residuals` be `assert len(r.dm.dm_data) <= len(wb_toas)`, not strictly less than?

In this case, by construction not all TOAs have DM data, and this is checking that that is reflected in the residual object.

> --Why in `test_wideband_residuals_dof` is the parameter `"DMJUMP"` set free? Shouldn't it be `"DMJUMP1"`? As an aside, is there a way to recover the condition each JUMP/DMJUMP parameter corresponds to? i.e., how would someone stumbling upon `DMJUMP1` know that it corresponds to the selection `-fe L-wide`?

Er. It should be DMJUMP1, and I should get an error for setting anything on DMJUMP. That's not good. I'm not sure how maskParameters work, but I think they have a `key_value` attribute that contains either `fe` or `L-wide`, and presumably another attribute that contains the other?

> --The assertion in the test that fails, `test_wideband_fit_dmjump`, should look for -10 not 10 (same as you have it in `test_wideband_fit_dmjump_all`). I know it currently fails because of not all TOAs having DMs, but as a hack, if you give each TOA an arbitrary DM and a really, really large DM uncertainty, then the test passes (checking DMJUMP1 == -10 within some reasonable atol). I know this is not what the test is after, but it's a sanity check that it should work.

Indeed, one of the later tests does use DMs on all TOAs and I had to set the result to -10. I should change that. (But getting the tolerances right is not trivial.)

**Comment by pennucci** [comment]
Yeah, in my own tests I had made the same typo -- leaving out the 1 on DMJUMP and was none the wiser.  I was pulling my hair out trying to figure out why I wasn't getting the numbers I expected.  So yeah, I think that should throw an error.

**Comment by aarchiba** [comment]
> Yeah, in my own tests I had made the same typo -- leaving out the 1 on DMJUMP and was none the wiser. I was pulling my hair out trying to figure out why I wasn't getting the numbers I expected. So yeah, I think that should throw an error.

Maybe file that as a bug? I'll try to fix it but the Parameter code is really hard to understand so it might take a while to figure that out.

**Comment by pennucci** [comment]
In the process, just trying to figure out where in the code to point to.

**Comment by paulray** [comment]
Ah, I see you got rid of all the occurrences of `scale_by_F0` and now there is a hardwired `m.F0` in the design matrix. 

I think the idea is that when you need a frequency to convert a phase to a time residual, you should call `get_PSR_freq()` which has a `modelF0` argument.  By default, this is True so it will just return the F0 from the model, but it already supports the mode of returning `d_phase_d_toa` to give the local frequency and #713 was planned to add another method that quickly evaluated the frequency taylor series instead of doing the full delay calculation.  Presumably supporting that will be held for a separate PR.

**Comment by aarchiba** [comment]
Ah, so there are *four* possible ways to handle phase -> time conversion:

- Use the full delay calculation (at what time? before or after delay corrections?)
- Use the Taylor series but don't worry about delay/timescales
- Use F0 from the model
- Use some fiducial F0 that is not a fit parameter

Since the existing `scaled_by_F0` did none of this (it decided on whether certain quantities were in phase or time units), I took it out and decided that implementing any of those other options belonged in some future PR.

**Comment by aarchiba** [comment]
Ready to merge, unless we want to delay this until we can correctly implement more sophisticated phase -> time conversion.

**Comment by pennucci** [comment]
FWIW, I just used WidebandTOAFitter to fit DMJUMPs for a couple of new pulsars in the 15y data set that do not already have DMJUMPs measured / aligned templates, and it returned sensible enough values.  I was previously using 12.5-year results for testing.  Again, the uncertainties (for DMJUMPs and DMX) are completely bogus, but it looks to do what it is supposed to do.

**Comment by aarchiba** [comment]
I think the DMJUMP uncertainties might be something we need to pursue in another PR.

**Comment by luojing1211** [comment]
I think this is good to go. Since this has some API optimizing, we should make sure this is ready for next. The scale_F0 part should not keep up from doing the busying week analysis. So I would say merge it and let the user test it.

**Pull request merged**
