### PR TITLE
Ecliptical coor

### PR DESCRIPTION
**Pull request by luojing1211**
Add Ecliptic coordinate. 
* Not test file yet. 
* Merge after the test file are pushed up.

### CODE REVIEW

**Comment by luojing1211** [comment]
Problem fix. Please try it out

**Comment by luojing1211** [comment]
This branch is ready to merge.

**Comment by demorest** [comment]
The ecliptic.dat file needs to be added to package_data in setup.py so that it gets installed (similar to how observatories.txt is done).

Also there are a couple mis-spellings in function or class names:  "load_obliqity_file" (in pulsar_ecliptic.py) and "AstrometryEquitoral" (in astrometry.py).

**Comment by demorest** [comment]
Several data files needed for test_B1855_9yrs.py are not present (B1855+09_NANOGrav_9yv1.tim and B1855+09_NANOGrav_9yv1.gls.par.tempo2_test).

Also "AstrometryEquitoral" is still misspelled.

**Comment by luojing1211** [comment]
Thank you Paul. Please check the newest update, if there is more missing files or issues, please let me know. 

-Luo Jing

**Comment by demorest** [comment]
The correct spelling is AstrometryEquatorial.  Needs to be fixed in tests/test_parfile.py alsa.

**Pull request merged**
