### PR TITLE
Doc/Notebook improvements

### LINKED ISSUE #555: tim file commands must be UPPERCASE
I tried using "include" in a .tim file to read in an included file. This works fine in Tempo2, but in PINT the parser does the comparison as cmd == "INCLUDE" so it requires the command to be all uppercase. Is this the desired behavior?  Should we support lower case commands, like Tempo2 does? Note that TEMPO seems to require all uppercase.

### PR DESCRIPTION
**Pull request by paulray**
This is a few doctoring and notebook improvements.
Also makes TOA line command parsing be case insensitive: Fixes #555

### CODE REVIEW

**Comment by paulray** [comment]
Also includes a partial fix for #558. At least it will raise an exception instead of quietly doing the wrong thing.  Full fix would still be useful.

**Comment by paulray** [comment]
OK, this passes and is ready to merge

**Comment by paulray** [comment]
OK, the black failure is wrong. I tried black on the files it specifies and no changes are needed.  Maybe there is some version difference?

**Comment by paulray** [comment]
I think this can be merged now. Then @kerrm can merge with his PR and it should test without errors (except for the bizarre black thing)

**Comment by paulray** [comment]
@aarchiba is it OK to ignore the black failures in travis and merge this now?  I can't replicate them on my machine:
```
mcxr2 : 35>black --check src tests examples
All done! ✨ 🍰 ✨
153 files would be left unchanged.
```

**Comment by kerrm** [comment]
19.10b?  how old and busted!  The glorious future over here has 19.3b0!

**Pull request merged**
