### PR TITLE
Profiling

### PR DESCRIPTION
**Pull request by luojing1211**
Add a little script for profiling. It is a generic profiling script.
Package required: 
cProfile
argparse
subprocess
pstats 
gprof2dot
for the last one see page. 
https://github.com/jrfonseca/gprof2dot

### CODE REVIEW

**Comment by paulray** [comment]
For directories like this, we should make sure that it is ignored by things like nosetests and coverage. I'm not exactly sure how to do this.

Also, this script should use `from __future__ import print_function` since we want all our code to by Python3 compatible.

**Comment by jellis18** [comment]
You should add `pint/profiling/*` to the `omit` section of `.coveragerc` and `- pint/profiling` to the `ignore-paths` section of `landscape.yml`. That way it won't be picked up by landscape or by coveralls.

**Comment by luojing1211** [comment]
Can we merge this branch?

**Comment by paulray** [comment]
I think you just need to change `print cline` to `print(cline)`

**Pull request merged**
