### PR TITLE
Moved example data to the correct location (src/pint/data/examples/)

### PR DESCRIPTION
**Pull request by abhisrkckl**
Fixes issue #1349 (and also issue #1345, which is a symptom of the more general issue #1349.)

### CODE REVIEW

**Comment by abhisrkckl** [comment]
Based on running grep:
 `J0613-sim.par.good` is not used in any of the scripts.
`NGC6440E.par.good` is used in `MCMC_walkthrough.broken` and `fit_NGC6440E_MCMC.py`
`J0030+0451_P8_15.0deg_239557517_458611204_ft1weights_GEO_wt.gt.0.4.fits` is used in  `MCMC_walkthrough.broken` 
`templateJ0030.3gauss` is used in  `MCMC_walkthrough.broken` 

`fit_NGC6440E_MCMC.py` should work after moving these files as it accesses the example files via `pint.config.examplefile` function. (I have tested this.)

I don't know about `MCMC_walkthrough.broken`. Maybe it is planned to be fixed in the future?

**Comment by dlakaplan** [comment]
Maybe it's better to remove those files which are not used by any example?

**Comment by paulray** [comment]
Please keep the NGC6440E and J0030 files.

**Comment by abhisrkckl** [comment]
I have also checked the test scripts. Only ` J0613-sim.par.good` can be safely deleted.

**Pull request merged**
