### PR TITLE
Piecewise spindown model

### LINKED ISSUE #883: prefixParameter time scale is wrong in all but the first parameter (_1)
If one adds the following line at glitch.py:180

```
            print(gnepnm, glep.quantity._time.__dict__)
```
it comes out that the timescale is "tdb" only in the first of the parameters in the series (e.g. "GLEP_1", not "GLEP_2")
I discovered this by working on a piecewise timing model

### LINKED ISSUE #887: AttributeError: 'Quantity' object has no 'rms_weighted' member
I'm having this problem with pintk, that might or might not be associated with some library version
I tried Astropy 4.2 and 4.0.

To reproduce:
```
$ pintk testtimes.par testtimes.tim

INFO: IERS B Table appears to be old. Attempting to re-download. [pint.erfautils]
Downloading http://hpiers.obspm.fr/iers/eop/eopc04/eopc04_IAU2000.62-now
|===================================================| 3.3M/3.3M (100.00%)         5s

(...)

arecibo TOAs (4):
  Min freq:      1500.000 MHz 
  Max freq:      1500.000 MHz 
  Min error:     2.94 us
  Max error:     2.94 us
  Median error:  2.94 us
gbt TOAs (4):
  Min freq:      1500.000 MHz 
  Max freq:      1500.000 MHz 
  Min error:     2.94 us
  Max error:     2.94 us
  Median error:  2.94 us

Traceback (most recent call last):
  File "/Users/meo/anaconda3/envs/py3/bin/pintk", line 33, in <module>
    sys.exit(load_entry_point('pint-pulsar', 'console_scripts', 'pintk')())
  File "/Users/meo/devel/spyder_projects/PINT/src/pint/scripts/pintk.py", line 172, in main
    app = PINTk(root, parfile=args.parfile, timfile=args.timfile, ephem=args.ephem)
  File "/Users/meo/devel/spyder_projects/PINT/src/pint/scripts/pintk.py", line 49, in __init__
    self.openPulsar(parfile=parfile, timfile=timfile, ephem=ephem)
  File "/Users/meo/devel/spyder_projects/PINT/src/pint/scripts/pintk.py", line 118, in openPulsar
    self.psr = Pulsar(parfile, timfile, ephem)
  File "/Users/meo/devel/spyder_projects/PINT/src/pint/pintk/pulsar.py", line 99, in __init__
    % self.prefit_resids.time_resids.rms_weighted().to(u.us).value
  File "/Users/meo/anaconda3/envs/py3/lib/python3.7/site-packages/astropy/units/quantity.py", line 835, in __getattr__
    attr))
AttributeError: 'Quantity' object has no 'rms_weighted' member

```

### PR DESCRIPTION
**Pull request by matteobachetti**
To do:

- [x] Test the derivatives
- [x] Field test with pintk or another fitter (works with pintempo; for pintk see #887)

Resolves #883
Resolves #887

Model components:
```
F0                          5

PWF0_1                  0.771552110 1       1
PWF1_1                 -5.0000E-14  1
PWF2_1                  0   1
# Epoch of solution
PWEP_1                  54658.2722693052565  
# Starting epoch of validity
PWSTART_1               54657
# Final epoch of validity
PWSTOP_1                54720.
# Initial phase of solution
PWPH_1                  0   1

PWF0_2                  0.771552110 1       1
PWF1_2                 -5.0000E-14  1
PWF2_2                  0   1
PWEP_2                  54658.2722693052565
PWSTART_2               54720.
PWSTOP_2                54763
PWPH_2                  0   1
```
Note: they need F0 to be defined, and the PWF0_x are _summed_ to it (Setting F0 to 0 makes everything crash miserably)
At the moment it only works up to the second derivative in each interval.

### CODE REVIEW

**Comment by paulray** [comment]
Sweet!

**Comment by matteobachetti** [comment]
Note that one of the test is failing due to #883 :(

**Comment by scottransom** [comment]
Agreed!  I can see using this....

**Comment by matteobachetti** [comment]
@paulray @luojing1211 et al.: ready for review

**Comment by matteobachetti** [comment]
There was another failure in pintk, related to string formatting, and I fixed it

**Comment by paulray** [comment]
Merging to get the pintk fixes!

**Pull request merged**
