### PR TITLE
Change obj velocity calculation method to astropy

### PR DESCRIPTION
**Pull request by luojing1211**
This is an update for solar system body's velocity calculation. Since astropy 1.3 has released, the velocity calculation is supported by astropy now. More detail see issue #207 

Note: This branch only works for astropy 1.3. Please update it.

### CODE REVIEW

**Comment by paulray** [comment]
I prefer not to update until MacPorts supports astropy 1.3.  As of now it is at 1.2 (https://www.macports.org/ports.php?by=name&substr=astropy).

Also, if this PR removes the need to download data files then that should be corrected at the same time.  Though, I assume it only removes the need for de*.bsp, not other files, right? I'm a bit confused about the datafiles scheme in PINT.  Initially, they are downloaded by `setup.py`, but there is also a `download_data.sh` script in the datafiles directory, however that script does not get copied to the installed directory.  If `download_data.sh` is obsolete, it should be deleted.  What do you think @demorest?   PINT should certainly include a function for the user to update the downloaded data files, but it needs to be able to update both the local copy and the installed files and I don't think `download_data.sh` does that.

**Comment by luojing1211** [comment]
Hi @paulray 

This branch does not remove the download files yet. The file is going to be removed is *.bsp files, definitely not other files.  `download_data.sh` was used at earily PINT development period. Since we are downloading those file in the `setup.py`, it is no longer used.

**Comment by luojing1211** [comment]
Hi @paulray and @all, 

I remove the download and check sum for *.bsp file in the setup.py. Since astropy will download and cache them internally, *.bsp file will not show up in our datafile directory. 

Also I added NASA ftp site for ephemeris link. Please check it out see if it can be improved.

**Comment by paulray** [comment]
Before this can be merged, setup.py should be updated with this line (currently it says 1.2):
```
install_requires = ['astropy>=1.3'],
```

**Comment by paulray** [comment]
MacPorts is now up to date with astropy 1.3, so people installing astropy with either MacPorts or pip will get 1.3.  To me, this means this PR is OK to merge.

**Comment by luojing1211** [comment]
I just realized that astropy download the ephemeris '.bsp' file as a format of cache file saved in the ~/.astropy directory other than a '.bsp' file. This maybe limit us for using the ephemeris that does not come from JPL site. 

Is this matters a lot to you @jellis18 and @all. To use astropy, we do not have to worry about downloading the '.bsp' files from jpl site, but we lost some control as the price.

**Comment by jellis18** [comment]
@luojing1211, ok just to be clear, it seems that `astropy` will always try to download the JPL ephemeris if it is not cached. In other words you can't point it to a `.bsp` file without it being cached or downloaded.

I really think that we want to have a decent amount of flexibility on the ephemerides especially since it appears that this could be limiting factor in GW detection and red noise modeling. There are French (http://www.imcce.fr/fr/presentation/equipes/ASD/inpop/) and Russian (I don't know the link) ephemerides that one may want to use. At least the French versions (I haven't tried the Russian version yet) are in spice format and can be read by `jplephem`. Maybe we could cache them the same way that `astropy` does so that it can be used?

Lastly, if `tempo2` has this functionality (which it does) then `PINT` should definitely have it :)

**Comment by luojing1211** [comment]
Hi @all 
I hecked astropy to allow astropy read data file from a local directory. I have to change the private attributes of solar_system_ephemeris class.  I don't know if it is the right thing to do, but it seems working. 
```
coor.solar_system_ephemeris._kernel = SPK.open(path + "%s.bsp" % ephem)
coor.solar_system_ephemeris._value = datapath("%s.bsp" % ephem)
coor.solar_system_ephemeris._kernel.origin = coor.solar_system_ephemeris._value
```
What do you think?

**Comment by paulray** [comment]
I actually already made the name change of objPosVel2SSB in my PR.  Hopefully they will merge smoothly.

**Comment by luojing1211** [comment]
I think this is ready. We should consider get this merged.

**Pull request merged**
