### PR TITLE
Make Py3 work

### PR DESCRIPTION
**Pull request by matteobachetti**
This is a series of fixes that should make tests work on Py3. 
A large part of them is about using dictionary keys as lists, which is not the case by default in Py3. There are a few minor subtleties, like modules with changed names, a different way to use metaclasses, integer division (Which is generally the most complicated thing to detect).

### CODE REVIEW

**Comment by matteobachetti** [comment]
@paulray Tests are passing. I disallowed failures in Py3 for clarity

**Comment by paulray** [comment]
Thanks for working on this!  What are `.keys` in Py3? It seems strange that you have to wrap them in `list()` in so many places. How would this have been done if the code were written natively in Py3?  Just curious.

**Comment by matteobachetti** [comment]
Dict keys are iterables in Py3, so the functionality is the same if you use them in loops, e.g. 
```
for i in blabla.keys():
    do_stuff_(i)
```
But they do not support item assignment. In Py 2 you could do something like `blabla.keys()[2]`, in Py3 it doesn't work anymore.

**Comment by matteobachetti** [comment]
In Py3, `list(blabla)` would also work, without asking explicitly for the keys

**Comment by paulray** [comment]
OK, thanks for the explanation! So, should we go ahead and merge?

**Comment by matteobachetti** [comment]
Yes, for me it's ready to merge

**Comment by jellis18** [comment]
I know this is merged but it may be cleaner to use something like
```
sorted_list = sorted(DMX_mapping.keys())
```
rather than
```
sorted_list = list(DMX_mapping.keys())
sorted_list.sort()
```

**Pull request merged**
