### PR TITLE
Fixing tutorial notebooks

### PR DESCRIPTION
**Pull request by dlakaplan**
Trying to get tutorial notebooks to work (#1137)

### CODE REVIEW

**Comment by dlakaplan** [comment]
The `docs/conf.py` file had the command:
```
nbsphinx_custom_formats = {".py": lambda s: jupytext.reads(s, ".py")}
```
to convert the `.py` tutorials to notebooks, but it didn't seem to be running.  However, the import for `jupytext` was commented out:
https://github.com/nanograv/PINT/blob/master/docs/conf.py#L20
This seemed to be part of:
3470a047ec14ec1d45aaa199cbfb17b322bfd95f
from @aarchiba, and I don't know what the intent was.

With that line restored, it seems to work.  Compare:
https://nanograv-pint--1154.org.readthedocs.build/en/1154/tutorials.html
to:
https://nanograv-pint--1026.org.readthedocs.build/en/1026/tutorials.html (an unrelated PR):
the tutorial notebooks do not build in the latter.

Still checking a few other issues, though.

**Comment by scottransom** [comment]
Nice job, @dlakaplan !

**Comment by dlakaplan** [comment]
Note that #1099  is still present, so the formatting isn't great.

**Comment by aarchiba** [comment]
Looks like just a slip on my part, and the exception was getting swallowed somewhere in the guts of Sphinx (maybe emitted but lost in the glut of messages). Fix is simple and effective. #1099 is another story...

**Pull request merged**
