### PR TITLE
update parameter print out control

### PR DESCRIPTION
**Pull request by luojing1211**
* Add a control flag for if the parameter will be printed out in the parfile.

### CODE REVIEW

**Comment by paulray** [comment]
Just to document my comment from the telecon, I worry that this functionality could cause bugs, if a parameter that has a non-default value gets set to not printing and then someone writes out a par file. That par file would then not be able to reconstruct the model correctly

**Comment by paulray** [comment]
Should we close this, or do we want to discuss it more?

**Comment by scottransom** [comment]
@paulray So you think that if you print a model, you should just get everything, right?  If so, I agree with that.  You can always edit it later....

**Comment by paulray** [comment]
Yes, and I don't see what problem this is solving. Is there an example of a parameter we don't want printed when we print as parfile?

**Comment by scottransom** [comment]
Fair enough.  I'm totally fine with closing it.  In fact, I think we should  probably have tests (and a corresponding PR) to make sure that we have all of the relevant things in a model always printed!

**Comment by paulray** [comment]
Good point @scottransom . A test that models can round trip to a par file would be good. Do we not have anything like this yet?  Great student project!

**Pull request closed without merging**
