### PR TITLE
Time derivatives of NE_SW (NE_SW1, ...)

### PR DESCRIPTION
**Pull request by abhisrkckl**
Complements #1854

### CODE REVIEW

**Comment by dlakaplan** [comment]
Maybe clarify that you are putting in time derivatives here (and not partial derivatives needed for fitting)?

**Comment by kerrm** [comment]
Two quick comments:
(1) perhaps add a short circuit for non time dependent cases to avoid any performance regression
(2) the test case should include a test of the correctness, e.g. that NE_SW1 = 1 produces a value of 5 a year 0 and 10 at year 5

**Comment by abhisrkckl** [comment]
> Two quick comments:
> (1) perhaps add a short circuit for non time dependent cases to avoid any performance regression
> (2) the test case should include a test of the correctness, e.g. that NE_SW1 = 1 produces a value of 5 a year 0 and 10 at year 5

Added both.

**Comment by abhisrkckl** [comment]
I think this is ready to merge.

**Pull request merged**
