### PR TITLE
WIP: Updating some basic info in the README

### PR DESCRIPTION
**Pull request by dlakaplan**
Also updating install docs

### CODE REVIEW

**Comment by dlakaplan** [comment]
[I'm trying to get some internal hyperlinks to work in the RTD build.  So far no luck.  If I'm doing something stupid let me know]

**Comment by scottransom** [comment]
@dlakaplan We talked about updating the README in today's telecon.  One thing that came up was to mention that people can use the #pint channel on the NANOGrav Slack if they have access to it.  And also that they can email pint@nanograv.org if they have questions they don't want to send to individual people.

I'm happy to merge what you have now and add those myself.  Or you can add them and merge if you are happy with the hyperlink situation.

**Comment by dlakaplan** [comment]
I added a mention of the slack channel and pint@nanograv.org (who does that go to?)

Probably won't mess more with the hyperlinks for now, but no rush on merging either.

**Comment by scottransom** [comment]
Let's merge it.  IMO this document can change often and in small amounts as needed.

**Pull request merged**
