### PR TITLE
Wishlist for PINT development

### PR DESCRIPTION
**Pull request by abhisrkckl**
As discussed in a previous meeting, I have collected a wish list of features and improvements for PINT.

### CODE REVIEW

**Comment by dlakaplan** [comment]
Is there supposed to be a way to claim or discuss individual items?

**Comment by abhisrkckl** [comment]
> Is there supposed to be a way to claim or discuss individual items?

This is a very important point. We should discuss this in the next meeting, I think.

**Comment by dlakaplan** [comment]
Would it be better to just include the wishlist in an issue or PR so that we can comment on it directly, rather than as a separate file?

**Comment by abhisrkckl** [comment]
As we have decided in the meeting, I have made an issue #1576 for this. I have pinned the issue so  that it appears on top.

**Pull request closed without merging**
