### PR TITLE
SciPy Version Fix

### PR DESCRIPTION
**Pull request by champagne-cmd**
Fix for Travis error involving SciPy v. >1.5.0 - `np.any` no longer accepts `Quantity` arrays. Wrapper function `minimize_func` now returns the `.value` of the result. ( addresses #736 )

### CODE REVIEW

**Comment by paulray** [comment]
The build failure is something about a docstring in polycos.py, which isn't modified in this PR. Not sure what is going on, but it shouldn't prevent merging this.

**Comment by paulray** [comment]
Chloe, do you have any idea why this scipy issue happened?  It is strange since `np.any()` is part of numpy, not scipy and `Quantity` is defined in astropy.  Also I believe numpy has been evolving to have better support for `Quantity`.

**Comment by champagne-cmd** [comment]
I'm afraid I don't know @paulray , I skimmed through the release notes for SciPy 1.5.0 but didn't see anything that immediately stuck out as being relevant. 
Also, this failure is occurring with #762 as well, so perhaps a pull request before yesterday caused the docstring error? I looked at the docstring though and it has closing quotes, so I'm not sure what the problem is there either.

**Comment by paulray** [comment]
I think I fixed the docstring in `nanograv/master`, so can you merge that into your PR?  That should fix the build failure

**Comment by paulray** [comment]
I thought about this a bit and I think a better fix may be to ensure that `resids.chi2` is not a quantity.  Right now it sometimes it, but sometimes isn't.  It is computed by `calc_chi2()` in either the `Residuals` or `WidebandDMResiduals(Residuals)` class.  Those can return `np.inf` which is not a Quantity, or a Quantity with dimensionless units, or a pure number (in the case when the model has a noise component and the chi2 is computed by the GLSFitter). So, I think that in the two `calc_chi2()` routines is where it should ensure that chi2 is a pure number, not a Quantity.

**Comment by champagne-cmd** [comment]
@paulray when I implement that, the test_model_ifunc.py fails because it uses chi2.value. Should this test be modified? Every other test passes that is suppose to pass.

**Comment by paulray** [comment]
Yes, I'd remove the .values from that test.

**Comment by champagne-cmd** [comment]
Closes #736

**Pull request merged**
