### PR TITLE
Include list of observatories in docs

### PR DESCRIPTION
**Pull request by dlakaplan**
Will include a list of observatories in the docs, including google maps URLs to check positions and clock files.  See:
https://nanograv-pint--1581.org.readthedocs.build/en/1581/observatory_list.html

### CODE REVIEW

**Comment by dlakaplan** [comment]
I don't know why that test is failing (not related to my PR).  But if somebody can look at the RTD output and give any feedback that would be great.  I'll fix the error eventually.

**Comment by dlakaplan** [comment]
I've added clock files with links to the global clock repository.  I'm linking to the human-readable pages (not the raw files).  I construct the URLs by:
`https://ipta.github.io/pulsar-clock-corrections/{format}/clock/{filename}.html`
where `format` is `tempo` or `T2runtime` depending on whether `clock_fmt` is `tempo` or `tempo2`.  I can't verify that this is correct with the global clock code, but it seems to work.  @aarchiba : are you able to confirm or fix?

**Comment by abhisrkckl** [comment]
I think this looks good. I'll merge this if it's ready.

**Comment by abhisrkckl** [comment]
I think that is fine.

**Comment by dlakaplan** [comment]
In that case, this is probably OK to merge now.

**Pull request merged**
