### PR TITLE
fix NGC6440E.par

### PR DESCRIPTION
**Pull request by abhisrkckl**
The example files `NGC6440E.par` and `NGC6440E.par.good` had unsupported `UNITS UTC(NIST)` and `T2CMETHOD TEMPO`. `PINT` was ignoring these lines with warnings and using `TT(BIPM2021)` and `IAU2000B` instead. I have changed these par files so that the warnings go away. This is the first step in addressing issue #1483. 

EDIT: I have also changed the warning for a "MODE" statement in the TOA file to be more informative.

### CODE REVIEW

**Comment by abhisrkckl** [comment]
There is also another warning about `MODE 1` in `NGC6440E.tim`. I have not removed it as I am not sure if that is required to use this file with `tempo` and `tempo2`.

**Comment by paulray** [comment]
I don't know if TEMPO or Tempo2 still default to not using TOA errors if MODE 1 is omitted. 
PINT could be changed to silently ignore MODE 1 with no no warning. If MODE 1 is omitted, PINT acts as if it was present.
I'm not sure what should happen if there is MODE 0 (which I've never seen). Does PINT even have the ability to ignore TOA errors?

**Comment by abhisrkckl** [comment]
> I don't know if TEMPO or Tempo2 still default to not using TOA errors if MODE 1 is omitted.

`MODE 1` is required by `tempo2` to use weighted least-squares. `tempo2` will use ordinary least-squares if `MODE 0` is given or if no `MODE` is specified.

**Comment by paulray** [comment]
Looks good. This can be merged as far as I am concerned.

**Comment by abhisrkckl** [comment]
This is ready to go, I think. The failing CI test is due to a connection issue at the ephemeris download server.

**Comment by abhisrkckl** [comment]
Closing this as this duplicates #1487

**Pull request closed without merging**
