### PR TITLE
Check for Mixed Coord. Systems in Par File

### PR DESCRIPTION
**Pull request by champagne-cmd**
Adds a check when reading in `.par` file to make sure POS and PM coordinate systems are the same.

### CODE REVIEW

**Comment by champagne-cmd** [comment]
@paulray two tests will fail in `test_model_manual` because they use a par file with mixed coordinate systems, `J1744-1134.basic.ecliptic.par`. It has `RAJ`, `DECJ`, and `ELAT` commented out and `ELONG` uncommented, and `PMRA` and `PMDEC`. I would comment out `ELONG` and uncomment `RAJ` and `DECJ`, but the file's name seems to suggest it is meant to be an ecliptic file. How should I modify this?

**Comment by paulray** [comment]
I think you should uncomment ELAT, so it has ecliptic position and equatorial proper motion. This *should* throw an exception, and that seems to be what is expected, since the tests is marked "xfail".

**Comment by luojing1211** [comment]
Hi @champagne-cmd, it looks good. I would give more explanation to the error message. 
For example, "Cannot have Ecliptic PM with Equatorial POS in par file", I would say, "Cannot have Ecliptic poper motion parameters (PMELONG/PMELAT) with Equatorial position parameters (RAJ/DECJ) in par file". You can also dynamically give the conflicted parameter names in the message, so the user would know which parameters are conflicting.

**Comment by champagne-cmd** [comment]
@paulray the two tests I was talking about are `test_compare_get_model_new_and_old_all_parfiles` and `test_get_model_roundtrip`, which aren't marked "xfail". The former is testing the `get_model_new` function, and the latter is testing the `as_parfile` function. I think maybe they are using this `.par` file when they shouldn't be, because other tests that are marked "xfail" use the `.par` file. Perhaps putting this `.par` file in the `bad_trouble` array is a solution.

**Comment by paulray** [comment]
I see, sorry! I agree that this bad par file (with mixed ECL and EQU coordinates) should be in the bad_trouble list.  That should solve it.

**Comment by champagne-cmd** [comment]
Fixes #654

**Pull request merged**
