### PR TITLE
Pintk update - add to stash

### PR DESCRIPTION
**Pull request by almcewen0**
This is a pretty small foray into pintk development, but I have added the ability to add to the stashed TOAs (mentioned in https://github.com/nanograv/PINT/issues/1203). If any TOAs are selected, they will be added to the stash. If none are selected, the stashed TOAs will be un-stashed (if there is nothing in the stash, nothing will happen).

### CODE REVIEW

**Comment by dlakaplan** [comment]
This sounds good.  Maybe just to help users could you add `log.debug` messages making clear what's happening?

i.e., "Adding X TOAs to the stash", "Adding Y additional TOAs to the stash", "Unstashing X TOAs"

or something like that?

**Comment by almcewen0** [comment]
i just found a bug in this (additional stashed TOAs are duplicated in the stash), but i don't have time to fix it right now. this shouldn't merged until i solve it.

**Comment by almcewen0** [comment]
Okay, i think the bug is fixed.

**Comment by dlakaplan** [comment]
Could you give some examples of the DEBUG messages?  And to show how this works can you share some screenshots or even a quick video?

**Comment by almcewen0** [comment]
> Could you give some examples of the DEBUG messages? And to show how this works can you share some screenshots or even a quick video?

Sure - here are a few screenshots to show the process and the messages. 

First, if there is nothing in the stash and nothing selected, pressing "t" will prompt that there is nothing to be unstashed:
Screen Shot 2022-09-27 at 16 13 04

If we then select a group of TOAs and press "t," a copy of the TOAs is saved to the stash, and the selected points are removed from the plot:
Screen Shot 2022-09-27 at 16 13 22
Screen Shot 2022-09-27 at 16 13 38
Screen Shot 2022-09-27 at 16 18 36

If we select another group and press "t" again, the selected TOAs are removed from the plot:
Screen Shot 2022-09-27 at 16 14 37
Screen Shot 2022-09-27 at 16 14 52
Screen Shot 2022-09-27 at 16 15 07

Note that the stashed TOAs don't actually change in that step, as they already include the second group of TOAs. 


Finally, if we press "t" one more time, the stashed TOAs will reappear:
Screen Shot 2022-09-27 at 16 15 26
Screen Shot 2022-09-27 at 16 15 17

**Comment by almcewen0** [comment]
Correct – DEBUG prints out all of the key presses.

From: David Kaplan ***@***.***>
Date: Wednesday, September 28, 2022 at 10:39
To: nanograv/PINT ***@***.***>
Cc: Alexander Eli McEwen ***@***.***>, Author ***@***.***>
Subject: Re: [nanograv/PINT] Pintk update - add to stash (PR #1393)

This looks good. Just to confirm: the "you pressed 't'" message was there before your changes, right?

**Comment by almcewen0** [comment]
> I think that looks really good. One minor comment: when no TOAs are selected maybe the message should be:
> "Nothing to stash/unstash"


done.

**Pull request merged**
