### PR TITLE
Fixed pintk bugs

### PR DESCRIPTION
**Pull request by juliadeneva**
Fixed 2 pintk bugs: empty tim file being written by clicking the 'Write tim' button under the residuals plot; and pintk reverting to the default DE421 ephemeris when 'Reset' was clicked instead of continuing to use the ephemeris specified in the par file.

### CODE REVIEW

**Comment by paulray** [comment]
Can you add UNITS TDB to all par files written by TimingModel.as_parfile() as well?

**Comment by juliadeneva** [comment]
Done, plus fixed a zima bug.

**Comment by paulray** [comment]
Thanks for all these fixes!  For --fuzzdays, can you change the default back to 0.0 and just put the part where it applies the fuzz in an if statement `if args.fuzzdays > 0.0:`.  For some applications, adding a 0.01 day fuzz to the TOAs by default would not be good.

**Comment by juliadeneva** [comment]
Ok, done

**Pull request merged**
