### PR TITLE
Plot model DM in pintk + more tests for pintk

### PR DESCRIPTION
**Pull request by abhisrkckl**
#457

### CODE REVIEW

**Comment by abhisrkckl** [comment]
image

**Comment by dlakaplan** [comment]
Does this behave properly for data with no DM or just a constant DM?

**Comment by abhisrkckl** [comment]
It works for constant DM:
image

The "model DM" radio buttons should be disabled when there is no dispersion component. I'll fix this.

**Comment by abhisrkckl** [comment]
>Does this behave properly for data with no DM

OK.. fixed this.
image

**Comment by dlakaplan** [comment]
great

**Comment by dlakaplan** [comment]
I'm confused by that screenshot: it looks to have 2 y-axis labels

**Comment by abhisrkckl** [comment]
> I'm confused by that screenshot: it looks to have 2 y-axis labels

That seems to be an unrelated bug. It shows up even without the changes in this PR.

**Comment by dlakaplan** [comment]
Can you figure out how to reproduce to file a separate issue?

**Pull request merged**
