### PR TITLE
Rerun intermittent failures in CI

### PR DESCRIPTION
**Pull request by abhisrkckl**
This was initially part of #1798 which was merged and then reverted.

### CODE REVIEW

**Comment by abhisrkckl** [comment]
The macos failure is because the runner is deprecated.

**Comment by dlakaplan** [comment]
I was also dealing with a situation like this, and in that case I just put in a fixed random seed so I know that it should pass if things work.  but I don't know if that's a good idea in general?

**Comment by abhisrkckl** [comment]
I think this is a more general solution. This also lets us know that we have a problem if the test fails even after 5 reruns.

**Comment by dlakaplan** [comment]
Since the new MacOS tests are no longer part of `tox.ini`, can you add the appropriate arguments to the git CI file?

**Comment by abhisrkckl** [comment]
> Since the new MacOS tests are no longer part of tox.ini, can you add the appropriate arguments to the git CI file?

Added.

**Comment by dlakaplan** [comment]
Looks good - should I merge?

**Pull request merged**
