### PR TITLE
Made SWXP frozen by default, even for first segment

### PR DESCRIPTION
**Pull request by dlakaplan**
#1826

### CODE REVIEW

**Comment by dlakaplan** [comment]
This may still not be perfect.  For the first segment, `SWXDM_0001` will still be unfrozen if the fit flag is not specified. i.e., 
for:
```
SWXDM_0001   0.0 
SWXP_0001   2
SWXR1_0001   53216.008946369795
SWXR2_0001   53505.07804959211
SWXDM_0002   0.0 
SWXP_0002   2
SWXR1_0002   53516.008946369795
SWXR2_0002   53605.07804959211
```
SWXDM_0001 is not frozen, while SWXDM_0002 is.  So there is a difference in how these are treated.

**Comment by dlakaplan** [comment]
OK, now I think it behaves correctly.

**Comment by mtlam** [comment]
Looks good to me, thanks, @dlakaplan!

**Comment by abhisrkckl** [comment]
This looks good. Shall I merge it?

**Comment by dlakaplan** [comment]
Yes, I think this is set.

**Pull request merged**
